### ISSUE TITLE
Remove redundant BeginBlock

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#1013]
Currently, the testing suite will call BeginBlock multiple times in a row. This is not an issue for now, but could become one if the `BeginBlock` logic ever changes.

The testing suite should be rearchitected to remove redundant BeginBlock calls.

See: https://github.com/cosmos/ibc-go/blob/main/testing/coordinator.go#L191

This will call BeginBlock 3 times in a row

**Comment by colin-axner** [comment]
I'm running into this call of [`BeginBlock`](https://github.com/cosmos/ibc-go/blob/46b2720687c3c34282002d8e50bb4f3262c5f035/testing/coordinator.go#L70) to be problematic. Might be best to tackle #1014 first so this is trivially removed

**Comment by danwt** [comment]
+1 as finding this problematic

**Comment by colin-axner** [comment]
short term solution is to [avoid that call](https://github.com/cosmos/ibc-go/pull/1169/files#diff-53fead689e01cbf19a4858fe0892cc7fa3d9cbbdb28969cc81dcafdc64b65d09R616)

I'd like to try to propose a fix in #1265

**Comment by danwt** [comment]
In addition to removing the redundant `BeginBlock` I'm having a related problem:

In many places for a pair of connected chains A, B, it is required to be able to call `.GetContext()`. But it seems impossible to get the context when the chain only did `EndBlock()`, and not `EndBlock();BeginBlock()`. This is unfortunate because you may not wish to `BeginBlock`.

**Comment by colin-axner** [comment]
This should be closed in the update to ABCI++ ref #3707 as begin, deliver, end block are squashed into a single FinalizeBlock so it wouldn't be possible to redundantly call begin block

Closing preemptively as these changes are inevitable so no need to track this issue
