### ISSUE TITLE
Add migration docs for 02-client refactor

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1202]
## Summary

The migration document should clearly explain how to go from the old 02-client API to the new API
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by catShaark** [comment]
can I try doing this ?

**Comment by crodriguezvega** [comment]
Sure, @catShaark. Thanks for volunteering!

Would it be possible for you to open a PR for this issue before the end of next week? As you can see in our [project board](https://github.com/orgs/cosmos/projects/7/views/14) this issue is part of our current iteration (ending April 29th) and the goal would be to complete these issues in the board to create an alpha tag.

@colin-axner would you like to add any more details in the issue of what you would like to see in the docs so that @catShaark can take that into account?

**Comment by catShaark** [comment]
@colin-axner thanks for the summary, I will dig into this and ask you if I get stuck.

**Comment by catShaark** [comment]
@colin-axner  should we add all the changes to core modules, like client keeper for example

**Comment by catShaark** [comment]
I want to add these entries :
- remove “09-localhost” client implementation
- client keeper CheckMisbehaviourAndUpdateState merge into UpdateClient
- MsgSubmitMisbehaviour is deprecated as MsgUpdateClient can handle header which include misbehaviour
- 07-tendermint client GetConsensusState has been modified
But I guess some of these might be irrelevant so I have to ask you

**Comment by colin-axner** [comment]
> @colin-axner should we add in that we remove "09-localhost" client implementation.

yes please!

> so I want to add these entries 

The only one I wouldn't include is:
- 07-tendermint client GetConsensusState has been modified

**Comment by colin-axner** [comment]
thanks @catShaark! Closed by #1287
