### ISSUE TITLE
Add simulations for 27-interchain-accounts app 

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#1352]
## Summary

Please support Cosmos-SDK [simulation](https://docs.cosmos.network/master/building-modules/simulator.html)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hey @alpe, do you have a specific use case in mind? What sort of support are you looking for? 

We haven't added simulation to IBC application before because we have previously deemed such changes too complex to implement for two simapps connecting to each other (simulating handshakes, client/connection/channel creation) and we deemed simulation support unnecessary. Simulations have historically been used to catch math bugs (staking, distribution etc), but the IBC applications thus far haven't not been very math heavy. 

We do have the [testing package](https://github.com/cosmos/ibc-go/tree/carlos/upgrade-sdk-0.46-tendermint-0.35/testing), but perhaps this is not sufficient for your use case? 

I'd love to see IBC testing expanded to include full integration tests and fuzz testing, but want to make sure we put our efforts towards the right solutions

**Comment by alpe** [comment]
Thanks for the feedback! I found simulations very helpful to detect integration issues in the past. Personally, I see them also as a mechanism to **plug in test sets** from different modules to the app, where they can add value without requiring people to have deeper knowledge of the module.
I do understand your point though, that ibc requires state which makes things more complicated.
If this makes sense for you, I can do a spike with one or two messages to get this started

**Comment by gosuri** [comment]
Hey guys, any ETA on when this will be merged? 

/cc @alessio

**Comment by crodriguezvega** [comment]
Sorry for the late reply... We're going to try to work on this in the coming 2 or 3 weeks. We will try to keep you all updated!
