### ISSUE TITLE
how to test SubmitMisbehaviour

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/ibc-go#1394]
## Summary
I want to broadcast submitmisbehaviour msg , but i found ,i cant build the message correctly 
firstly, i get header through the cmd  `cli query ibc header ` ,but i found the trustValidator will be nil 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Do you have valid misbehaviour to submit? You likely need two headers. The `trustValidator` is the validator set of the trusted header you are proving against. You have to submit that since ibc-go maintains minimal information on chain for proof verification

**Comment by ItsFunny** [comment]
Sry for the late response ,and thanks your replay .

Currently  I dont have any misbehaviour to submit , Can you tell me how could I create this by cli ?

**Comment by colin-axner** [comment]
> Can you tell me how could I create this by cli ?

Misbehaviour can't really be trivially generated via cli since you need chains to misbehave. For example, a chain's validator set would need to double sign on two different headers for the same height. It'd be helpful to know why you want to test misbehaviour submission. I'd suggest looking at the [support](https://github.com/cosmos/ibc-go#support) section on our README to see if there's a communication channel that we could help you more effectively on
