### ISSUE TITLE
All gRPC tests should use new testing package

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#143]
## Summary

In #140 I noticed some gRPC tests were not using the new testing package. The test case that `req = nil` can only be tested with the new testing package. We should update all tests and remove any old testing code for this setup. It is much easier to maintain the new testing code 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think the idea would be to get rid of `queryClient` field in the test suites for:

- [ ] [transfer](https://github.com/cosmos/ibc-go/blob/e093d85b533ab3572b32a7de60b88a0816bed4af/modules/apps/transfer/keeper/keeper_test.go#L34)
- [ ] [29-fee](https://github.com/cosmos/ibc-go/blob/e093d85b533ab3572b32a7de60b88a0816bed4af/modules/apps/29-fee/keeper/keeper_test.go#L63)
- [ ] [02-client](https://github.com/cosmos/ibc-go/blob/e093d85b533ab3572b32a7de60b88a0816bed4af/modules/core/02-client/keeper/keeper_test.go#L130)

And use call instead the gRPC endpoint using the method in the keeper. For example: for transfer instead of doing `suite.queryClient.DenomTrace`, call `suite.chainA.GetSimApp().TransferKeeper.DenomTrace`.

**Comment by expertdicer** [comment]
Can you please review my changes? Thank you
