### ISSUE TITLE
better documentation for upgrading ibc-go 

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#1450]
currently we have migration docs which are good but we have received feedback from @ValarDragon @assafmo that having something like [this diff PR ](https://github.com/osmosis-labs/osmosis/pull/1564/files) which shows ie: necessary imports would be really helpful for devs looking to upgrade to newer versions of ibc-go

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by assafmo** [comment]
I think that a demo repo with diffs to upgrade from v1 to v2, v2 to v3, etc. will go a long way here. It'll also show how to properly write upgrade handlers and how to evolve them over time.

**Comment by colin-axner** [comment]
Thanks for the feedback y'all. Upgrading versions of ibc-go should be as painless as possible. I originally added the migration docs because of how difficult I felt upgrading SDK versions was and I did not want that to be true for ibc-go. I'd really like to see the migration docs we have improved as it is really just what I scraped together for the v1 release of ibc-go and it hasn't changed much since then. 

Could y'all help me understand in more detail the exact issues that are being faced. Are the migration docs difficult to navigate? Do they have insufficient information? Are they too vague? Or do they provide too much information? Are bugs getting through after upgrading versions of ibc-go? Are there sections that require upgrades that we do not provide any information for? Is it difficult to review ibc-go bump prs (due to too many diffs)? Are there new additions to the codebase that weren't indicated in the docs?

I'm guessing if a diff pr is the suggested solution here, then one difficulty is that the migration docs aren't explicit enough. That the desirable behaviour is for them to explain how the before looked/behaved and how the after should look/behave. I'm somewhat uncertain a diff pr will always be the optimal solution for both us (maintainers) and y'all (chain developers) as it adds a bit of maintenance burden to us and the diffs could be quite massive. It doesn't seem useful to have 30 files of import/name changes in my opinion as it just adds noise. I think a single diff showing the change would likely be easier to comprehend/follow

I don't want to jump too far ahead to solutions until I understand the problem better, but before I forget, this is one idea I thought of. We could maintain an upgrading check list which has a box for every change a chain developer needs to do. It would start from our latest supported version (v2) and have check boxes all the way up to the latest released version (v4 atm). Each check box would have a short description of the change to be made and link to more detailed information down below in the document. There should also be a check box for each potential change a chain might need to make. Then chains could copy/paste this doc and check off each box as pr's come into a feature branch which would bump the ibc-go version. It might look something like this (information used may be incorrect, just using as an example):

--- 

## v5

- [ ] bump import path to v5
- [ ] asdf
- [ ] asdf

## v4

- [ ] bump import path to v4
- [ ] aadf
- [ ] asdf

## v3

This version introduces ICS 27 - Interchain accounts

- [ ] bump import path to v3
- [ ] [Add ics27 to SDK AppModule list](#links-to-section-below) (if integrating the ics27 host module)
- [ ] adsf

v2 

- [ ] bump import path to v2
- [ ] asdf
 
---

#### Adding ICS 27 host to SDK AppModule

The ICS 27 IBC application module must be added to the SDK AppModule list within app.go.

```diff
[]module.AppModule{
        ...
        ibc.NewAppModule(app.IBCKeeper),
+	ica.NewAppModule(nil, app.ICAHostKeeper),
	params.NewAppModule(*app.ParamsKeeper),
        ...
}
```

**Comment by ValarDragon** [comment]
> I'm guessing if a diff pr is the suggested solution here, then one difficulty is that the migration docs aren't explicit enough. That the desirable behaviour is for them to explain how the before looked/behaved and how the after should look/behave. I'm somewhat uncertain a diff pr will always be the optimal solution for both us (maintainers) and y'all (chain developers) as it adds a bit of maintenance burden to us and the diffs could be quite massive. It doesn't seem useful to have 30 files of import/name changes in my opinion as it just adds noise. I think a single diff showing the change would likely be easier to comprehend/follow

Err, I think theres a discrepancy in viewed diff, not sure how we hit 30+ files changed. Presumably IBC-go maintains a simapp

The suggested diff is a PR like (https://github.com/osmosis-labs/osmosis/pull/1564/files):
* Adding an upgrade handler with relevant logic
* Adding relevant new keepers / module basic / ibc router update
* param setting, etc.
I do agree that a lot of this becomes no longer necessary, with just needing to show:
* New keeper updates
* Param updates
given more upgrading dev UX wins. (e.g. v3.2.0 using a migration handler, made it super easy)

e.g. the following lines are present in your app.go and not really something you'd expect. (Though ideally this can become complexity that isn't by default exposed to app-devs, and only gets exposed if someone wants to override stuff)
```golang
	icaHostIBCModule := icahost.NewIBCModule(*appKeepers.ICAHostKeeper)
	// Create static IBC router, add transfer route, then set and seal it
	ibcRouter := porttypes.NewRouter()
	ibcRouter.AddRoute(icahosttypes.SubModuleName, icaHostIBCModule).
		AddRoute(ibctransfertypes.ModuleName, transferIBCModule)
```
Bumping the import path is a non-issue.

**Comment by colin-axner** [comment]
I think the main issue with a diff pr for our simapp is that it runs in the same go.mod so changes are made across many pr's, though we do have plans to give the testing package its own go.mod, which means then we could always bump the go.mod in a separate pr and link that pr

> Err, I think theres a discrepancy in viewed diff, not sure how we hit 30+ files changed. Presumably IBC-go maintains a simapp

Yea sorry, I was thinking more of app/light client dependencies. I realize chains will only have a few files

> 
> - Adding an upgrade handler with relevant logic
> - Adding relevant new keepers / module basic / ibc router update
>    param setting, etc.
>  - I do agree that a lot of this becomes no longer necessary, with just needing to show:
> - New keeper updates
> -  Param updates
> -   given more upgrading dev UX wins. (e.g. v3.2.0 using a migration handler, made it super easy)

Makes sense. I guess we can link the simapp.go pr changes (several prs) for now until we add the testing package as its own go module. 

> Also I'd suggest a test we can import from IBC, and use in some module, to ensure that its configured correctly. (E.g. ibc.TestHostICAIntegration(ctx, baseapp, keepers), and if that passes we know were good / nothing to worry about for the feature)

Already on the todo list #2027

**Comment by crodriguezvega** [comment]
I discussed with @colin-axner and we think our upgrading docs have improved in the last few releases, so we will close the issue, but feel free to open a new one if there's anything specific that we could do improve them further.
