### ISSUE TITLE
refactor: Consensus state key

### ISSUE THREAD

**Issue by catShaark** [cosmos/ibc-go#1483]
## Summary

We have problem where a `ConsensusStates` gRPC query return in lexicographic ordering of `Height`, not numerical ordering. For example:
```
  Here is an example (trimmed from an actual query). If the chain has states for heights:
  830, 821, 766, 222, 104, 76, 30, 25, 20, 10
  The gRPC query (`QueryConsensusStatesRequest`) returns:
  10, 104, 20, 222, 25, 30, 76, 766, 8, 821, 830
```
_This problem is originally posted in this [issue](https://github.com/cosmos/ibc-go/issues/1399)

## Proposal

We index `ConsensusState` by converting `Height.RevisionNumber` along with `Height.RevisionHeight` directly to 16 bytes ( 2 uint64 -> 16 bytes, big-endian ) in instead of turning them into a string ( uint64 -> string + "-" + uint64 -> string ) and then to bytes.

Specifically :
- Add Byte() method to `exported.Height` interface
- Implement Byte() for `02-client.types.Height`,  we turn `RevisionNumber` and `RevisionHeight` to 16 bytes (like described above) and return that 16 bytes
- Change `ConsensusStateKey()` so that they use `Height.Byte()` to create key for `ConsensusState` instead of using `Height.String()`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for thinking about this problem, @catShaark. I think the solution that you propose is very clever! 

Yes, so indeed we would need to run a migration to update the keys in the store... I think it's not a huge problem; we could release this as part of v4.0.0. We should make sure that we document the migration properly in the migration docs and that we thoroughly test it (both in integration and manual tests) to make sure it works well.

I guess the alternative would be otherwise to keep the the store key as is but then try to do the order in code after retrieving the consensus states from the store...

**Comment by crodriguezvega** [comment]
On a second thought we might have a problem with this approach, since relayers will probably need to update their code to retrieve consensus state proofs from the updated path. So, for example in Hermes, they would need to [update this path](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/core/ics24_host/path.rs#L57-L68). The problem comes here that relayers would need to support both paths (since some chains would be running the old path and some chains the new one, until all of them upgrade to the new path) but there would be no way (unless we implement something) for relayers to know which path to use.

So even though I think the idea is good, the practical issues of deploying it might be too difficult to overcome...

**Comment by catShaark** [comment]
> On a second thought we might have a problem with this approach, since relayers will probably need to update their code to retrieve consensus state proofs from the updated path. So, for example in Hermes, they would need to [update this path](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/core/ics24_host/path.rs#L57-L68). The problem comes here that relayers would need to support both paths (since some chains would be running the old path and some chains the new one, until all of them upgrade to the new path) but there would be no way (unless we implement something) for relayers to know which path to use.

Ohhh, I see, that's one annoying drawback that we have.

**Comment by catShaark** [comment]
thanks for the clarification @AdityaSripal :100:
