### ISSUE TITLE
New gRPC endpoint to query for connection `GenesisState`

### ISSUE THREAD

**Issue by adizere** [cosmos/ibc-go#1628]
## Summary

Is there a way to query for GenesisState of connection?
https://github.com/cosmos/ibc-go/blob/d0599131441f29c22f789672667fc527da295b37/proto/ibc/core/connection/v1/genesis.proto#L11

In the relayer implementation, we need to programatically obtain the `Params` in there.

## Problem Definition

Why do we need this feature? 

We need the `Params` specifically for `max_expected_time_per_block` which is essential in the implementation of connection (block) delay

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
I believe there is a way. If I understand correctly, the information you want is simply the current value of the `max_expected_time_per_block`, not necessarily the genesis value (since it is a param, gov can change it over time). If so, params has it's own [grpc](https://github.com/cosmos/cosmos-sdk/blob/main/x/params/keeper/grpc_query.go#L17). I believe the [subspace](https://github.com/cosmos/cosmos-sdk/blob/6473e733d6d300f330b54ea2a35af2aed042765f/x/params/types/proposal/query.pb.go#L35) is "ibc" (I may be mistaken), and the key is [this](https://github.com/cosmos/ibc-go/blob/80175911e3fe62f5ad98567c4127d6b45742ff88/modules/core/03-connection/types/params.go#L14)

The SDK has plans to remove x/params in the future, so future versions may require IBC to manage our own parameters, in which case we will expose a similar grpc for retrieving this value

**Comment by colin-axner** [comment]
I opened #2069. We will try to integrate this gRPC early so that when x/params are deprecated, most chains should support the params gRPC associated with 03-connection

**Comment by adizere** [comment]
Thanks Colin & Carlos for shepherding this request.

I think the present issue #1628 can be closed in favor of #2069. The latter issue should be sufficient for operator needs, in particular for https://github.com/informalsystems/ibc-rs/issues/2037 and implementation of connection delay.

**Comment by crodriguezvega** [comment]
Thanks, @adizere!
