### ISSUE TITLE
Why is the IBC module name, ibchost.ModuleName

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/ibc-go#1667]
## Summary of Bug

Something I find confusing in dealing with the app wiring, is that the core `IBC` module's moduleName (https://github.com/cosmos/ibc-go/blob/main/modules/core/module.go#L43-L46) is `ibchost.ModuleName`. (In osmosis / most apps atm we alias that host import to be ibchost)

I erroneously thought this related to interchain accounts host, whereas really the begin block here is for updating IBC clients.

Could the location / name of this module name be moved around? (Perhaps even keeping it in the same folder?)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
We could move it to our [exported directory](https://github.com/cosmos/ibc-go/tree/main/modules/core/exported). I agree it's an odd place to put the module name. It isn't in the types because the types because our types depend on submodules and our submodules depend on the ModuleName

Would it seem more logical if you used `ibcexported.ModuleName`?

**Comment by ValarDragon** [comment]
yeah `ibcexported.ModuleName` would be nicer!
