### ISSUE TITLE
Log handshakes as previous state UNINITIALIZED

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1688]
## Summary

When logging during the INIT and TRYOPEN steps of the handshake for both connection and channel. Change the previous state from `NONE` to `UNINITIALIZED`. See [comment](https://github.com/cosmos/ibc-go/pull/1672#discussion_r915844663)

Should be applied to both 03-connection and 04-channel handshake steps. Please assign yourself or comment on the issue if you will be handling it. May be backported. 

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Hi @GNaD13. Sorry, I missed your message and just saw it now... I think I am going to close this issue now, because its partly solved by https://github.com/cosmos/ibc-go/pull/3384 and it will be completely solved with https://github.com/cosmos/ibc-go/issues/3385. Thank for volunteering, I hope you can find another issue to work on. :)
