### ISSUE TITLE
What SDK code hash was this extracted from ?

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ibc-go#188]
Would be good to say explicitly in the CHANGELOG what commit hash of the SDK this was forked from. Presumably its something after v0.42.0 and contains `3bbda1430c1833983f66857a12d84166ff627a5a `, the last commit in the SDK to change the `x/ibc` module.

I was looking to make a change to the ibc CLI (add `query ibc-transfer escrow-address` so we can get the address for each channel so we can easily see how many coins are escrowed in a channel) but I guess I'll have to make the PR both to the SDK and to this repo ?

**Comment by colin-axner** [comment]
I can add the commit IBC was removed from the SDK and brought here `da064e13d56add466548135739c5860a9f7ed842`, but I'm not sure I follow why that'd be useful

Due to error and proposal type registrations, the IBC code cannot live in the SDK and here simultaneously. So IBC was removed during the 0.43.0 development cycle. We have to wait for an SDK v0.43.0 before we can officially do a release since we cannot depend on v0.42.x versions. 

I don't see backporting as necessary (I think it is probably possible to use the newer cli against older nodes), but if we did backport it, it would be against SDK's `release/v0.42.x` branch. You'd need to fix the imports when backporting

Does this explanation help?

**Comment by colin-axner** [comment]
I can add a note to the changelog indicating that backports should be to the SDK `release/v0.42.x` branch

**Comment by ebuchman** [comment]
RIght I was mostly just looking to ensure that any changes that are happening to IBC in the SDK repo (like the command I just added) will be replayed in this repo. It looks that command would be the first instance of that. Otherwise probably just good practice to include the hash somewhere for historical/verifiability reasons so people looking back can understand when this branched out.
