### ISSUE TITLE
Add Params gRPC for 03-connection

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2069]
## Summary

Same reasoning as #2066. Should be added for 03-connection params

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
For reference: https://github.com/cosmos/ibc-go/issues/1628#issuecomment-1253528327

**Comment by crodriguezvega** [comment]
The implementation for transfer can serve as reference. See this [comment](https://github.com/cosmos/ibc-go/issues/2066#issuecomment-1272935612) for details.

**Comment by damiannolan** [comment]
I think we need to go with some alternative naming. e.g. rename the `Params` grpc in 02-client to `ClientParams` and use `ConnectionParams` here.

Otherwise we cause `duplicate method: Params` compiler errors due to: https://github.com/cosmos/ibc-go/blob/main/modules/core/types/query.go#L15

What do you think?
