### ISSUE TITLE
`MsgTransfer` fails for solo machine client

### ISSUE THREAD

**Issue by devashishdxt** [cosmos/ibc-go#209]
## Summary of Bug

In the handling of `MsgTransfer`, the code calls `GetTimestampAtHeight()` ([here](https://github.com/cosmos/ibc-go/blob/4db5fd11cc83c0324261e4e7a6ba63dab4261ea7/modules/core/04-channel/keeper/packet.go#L87)) when sending IBC packet to solo machine. `GetTimestampAtHeight()` is called with height returned by `clientState.GetLatestHeight()` (this returns the sequence stored in `clientState` for solo machine).

As the code increments the sequence at many places and does not store `consensusState` for new height (or sequence), `GetClientConsensusState()` fails (which is called inside `GetTimestampAtHeight()`). I've tried sending `MsgUpdateClient` before sending `MsgTransfer` but, even in the handling of `MsgUpdateClient`, the code increments the sequence of `clientState` (making it `header.sequence + 1`) and stores `consensusState` for `header.sequence`.

So, at all times, there seems to be is no way of getting `consensusState` for `clientState.GetLatestHeight()`.

## Version

`master`

## Steps to Reproduce

1. Create a solo machine client on IBC enabled chain (using https://github.com/devashishdxt/ibc-solo-machine).
2. Send `MsgUpdateClient` and then `MsgTransfer`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Thanks @devashishdx for testing the solo machine! `GetTimestampAtHeight()` is quite problematic for solo machines and is also blocking timeouts from [working](https://github.com/cosmos/ibc/issues/562#issuecomment-820295032)

We have a long term solution in mind for how to fix this effectively, but this requires a bit of work and due to the current resource constraints, I don't expect a fix until earliest sometime in the late fall

The only short term solution I can think of is hard coding a bypass check for solo machines. That is, if the client is a solo machine, skip the timeout check

The timeout is also a defensive check, but I think it is nice to have. Pinging @cwgoes 

cc @AdityaSripal

**Comment by cwgoes** [comment]
This check is defensive and can safely be skipped for solo machines. I suppose we could store past timestamps along with sequence numbers, but that adds extra storage cost for a defensive-only check - not desirable.

If we add a bypass for solo machines now, in the future we should change the abstraction to make it less awkward.
