### ISSUE TITLE
interchain accounts controller chains need to import msg types from other chains for SendTx

### ISSUE THREAD

**Issue by charleenfei** [cosmos/ibc-go#2397]
## Summary

currently, the controllerkeeper SendTx function expects the InterchainAccountPacketData Data to be constructed via the helper function icatypes.SerializeCosmosTx, which takes in an array of sdk.Msg types. 

basically, to construct the right Data we would need to import the types package for the Msgs (which creates conflicts if the chain we are trying to import the types from is on a different ibc-go version),

or recreate the proto but using the package name specified by the host chain and take out the section of the helper function that takes an sdk.Msg type (because we would have to reimplement the Msg functions) (see our cosmoverse demo for this workaround). this should be better documented if it's the way forward.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Can you provide examples of the issue you faced? I'm having a hard time following. Applications should provide the host chain cdc with the host chain msgs to [SerializeCosmosTx](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/types/codec.go#L28). This should not be called from the controller chain perspective, the controller chain should be taking in bytes for the tx which will be executed on the host

**Comment by AdityaSripal** [comment]
> Applications should provide the host chain cdc with the host chain msgs to SerializeCosmosTx

So the usecase we built was the state machine itself sending the ica message.

So the controller chain state machine needed to create and marshal the ica messages.

So the first approach we took was to simply import the types package of the host chain (simpledex) that had the message we wanted to send in the controller chains ica caller module module (eightball). Then the eightball module used the constructor function in simpledex/types to create the sdk.Msg (MsgSwap) and called `SerializeCosmosTx`.
This approach didn't work because the two chains were using different versions of ibc-go, so we got an import cycle issue.

So then we just copied the MsgSwap proto file into our proto package. We then created our own MsgSwap and sent it over to the host chain. This failed on the host name because the msgtype url was not registered on the host chain codec (since the package names were different)

Finally, we copied the proto file to the controller chain repo but we kept the package name the same so the msg url stayed the same as well. We still ran into the issue in using the serializing helper function because it expected an sdk.Msg and our generated proto message didn't implement sdk.Msg. So either we have to copy over the sdk.Msg implementation of simpledex.MsgSwap or we change the helper serialize function to not take in an sdk.Msg on the controller chain.

The deserialize function on the host chain should still deserialize to a sdk.Msg

**Comment by AdityaSripal** [comment]
Afaik, we haven't tested cases where controller is sending host chain a msg that it doesn't actually use and the chains are on different versions. We faced this case in our workshop, ran into issues, and figured out how to do it:

Copy over the msg proto under the same package name and path, and generate the pb.go on our side.

https://github.com/charleenfei/cosmoverse-workshop/blob/main/proto/simpledex/simpledex/swap.proto

We also implemented this function:

https://github.com/charleenfei/cosmoverse-workshop/blob/3e1d51b93d788167fdd10c95eeb72c0731fd8aa4/x/eightball/types/codec.go#L35

So that we can serialize the tx's without having the MsgSwap implement sdk.Msg on the controller chain. If you notice it is the exact same implementation as `SerializeCosmosTx` it just doesn't expect the argument to be `sdk.Msg` which was unnecessary in the first place.

So here is the proposal:

1. Change `SerializeCosmosTx` to take in `proto.Message` instead of `sdk.Msg` (you can copy the helper function linked above)
2. Document how to handle the case where the controller chain wants to send messages that it does not implement.

**Comment by colin-axner** [comment]
> This approach didn't work because the two chains were using different versions of ibc-go, so we got an import cycle issue.

Can you go into more detail here? It'd help me understand the exact issue. 

Started looking into this, I'm a bit confused why the compiler is importing testing packages from ibc-go. My understanding was the testing files are not exported:

```
github.com/charleenfei/cosmoverse-workshop/x/eightball/keeper imports
	github.com/charleenfei/simple-dex/simple-dex/x/simpledex/types imports
	github.com/cosmos/ibc-go/v3/modules/core/02-client/types tested by
	github.com/cosmos/ibc-go/v3/modules/core/02-client/types.test imports
	github.com/cosmos/ibc-go/v3/testing imports
	github.com/cosmos/ibc-go/v3/testing/simapp imports
	github.com/cosmos/cosmos-sdk/x/auth/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.2), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/client/rest
```

> So here is the proposal:
>
>   1. Change SerializeCosmosTx to take in proto.Message instead of sdk.Msg (you can copy the helper function linked above)
>   2. Document how to handle the case where the controller chain wants to send messages that it does not implement.

Sounds good to me

**Comment by colin-axner** [comment]
Tagging `needs discussion` since I think it'd be useful to continue looking at potential work flows/solutions for this problem

**Comment by 0xekez** [comment]
it feels to me that the issue here is that the `sdk.Msg` protobuf is appearing in an on-the-wire message at all. who, other than another SDK go module, can possibly hope to interoperate with this?

> @colin-axner Applications should provide the host chain cdc with the host chain msgs to [SerializeCosmosTx](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/types/codec.go#L28). This should not be called from the controller chain perspective, the controller chain should be taking in bytes for the tx which will be executed on the host

i think this requirement makes the current cosmos SDK interchian accounts implementation nearly unusable.

1. expecting applications to serialize messages in terms of the `sdk.Msg` type is a high bar. imagine a non-SDK code trying to programatically interact with the ibc-go ICA implementation. it would need to find the protobuf definitions for the host chains `sdk.Msg`, and encode it using one of the [two](https://github.com/tendermint/go-amino) [forks](https://github.com/cosmos/gogoproto) of protobuf that the SDK uses. further, imagine requiring a smart contract to serialize `sdk.Msg` objects like this.. i think the ICA specification either needs to be much more clear about how this serialization happens so that a non-SDK-expert can figure out how to do this serialization, or it is extremely hard to interoperate with the current verison. you need the ability to do this serialization and deserialization to programatically interact with interchian accounts because protocols want to transform events on one chain, to events on another.
2. the current [SDK ICA implementation](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/types/metadata.go#L101) errors if a controller tries to connect to it using any encoding format other than "proto3" (whatever that means, per earlier the comment about which protobuf fork is being used for encoding). it feels that the correct behavior should be to "negotiate" and respond with metadata suggesting that "proto3" be used in the open-init handshake step, so that the controller can either adjust to this encoding, or otherwise cancel the connection.

these points together mean:

1. it is hard (if not impossible in the case of non-go smart contracts) to programatically interoperate with the ibc-go ICA implementation as the implementation provides no guidance on how to serialize the `sdk.Msg` type.
2. any controller module that prefers a different message type over `sdk.Msg` and attempts to connect to the ibc-go ICA implementation will have their connection rejected, and can not programatically negotiate to use the "proto3" wire format.

my suggestion would be to throw out using `sdk.Msg`, and use JSON which is used in both ICS-721 and ICS-20 as the on-the-wire packet format. for example, CosmWasm already has a [well used JSON version](https://github.com/DA0-DA0/dao-contracts/blob/0d815ae595aa89d9df3471745765d08d72f5f7b5/contracts/proposal/dao-proposal-single/schema/dao-proposal-single.json#L779-L891) of CosmosMsg that could be used.

allowing additional negotiation over the encoding format per point (2) would make it "technically possible" to interoperate with this ICA implementation, though this doesn't ameliorate the difficulty of doing so discussed in (1) like using JSON on the wire would.

**Comment by colin-axner** [comment]
Hi @0xekez, apologies for the late reply. We discussed your comment a while back internally, but I haven't had the time to reply until now. 

You make great points about the usability of proto from a smart contract developer point of view and I believe these concerns should be eased once we add functionality for json/rlp encoded ica transactions. The usage of `sdk.Msg` is still required for the time being as the host module on ibc-go can only execute msgs via the msg handler which expects an `sdk.Msg`

**Comment by colin-axner** [comment]
`SerializeCosmosTx` was changed to take `proto.Message` instead of `sdk.Msg` which I believe addresses the primary concern of this issue. Closing
