### ISSUE TITLE
Add support for ETH2 Light Client

### ISSUE THREAD

**Issue by jinankjain** [cosmos/ibc-go#2534]
## Summary

In order to bring IBC to Ethereum (ETH), we would need to add support for ETH Light Client in the ibc-go repo, so all the Cosmos-based chains would be able to communicate with ETH using IBC.

## Problem Definition

I think the need for this feature is very well justified as this would help all cosmos-based app chains communicate with ETH using IBC.

Currently, if someone would like to transfer tokens from ETH to a Comos-based appchain and vice-versa, then they would need to use custodial bridges which defines their own custom interfaces instead of IBC which is the de facto standard to transfer token between Cosmos-based appchains. All these bridges don’t expose the same IBC interface that all the Cosmos developers love to use. Thus, it would be great if we can bring the same IBC interface that is being used to communicate with other appchains. This would also improve the overall security as well since we would be light clients on both ends to validate the transactions.

## Proposal

We would implement ETH2 Light Client specification as mentioned here: https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md

More details about the architecture are laid out in this article: https://ethresear.ch/t/bringing-ibc-to-ethereum-using-zk-snarks/13634

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
@jinankjain I will close this issue for now, since there's no concrete action for us to take at the moment (we don't have plans to implement an ETH light client in the foreseeable future). With the changes being introduced in ibc-go v7.0.0 light clients will need to [implement the `AppModuleBasic` interface](https://ibc.cosmos.network/main/ibc/light-clients/setup.html), so they can be regular SDK modules living in their own repositories (and therefore no need for them to be part of ibc-go). See [this PR for an example with 07-tendermint](https://github.com/cosmos/ibc-go/pull/2825). Once there's an implementation of an ETH light client we can add it to our [registry](https://github.com/cosmos/ibc-go#ecosystem).
