### ISSUE TITLE
Allow localhost enabling to be a parameter

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#2537]
Perhaps we should add a parameter that allows chains to enable or disable localhost on their chain

This would then be checked in the localhost verification case to ensure it is enabled. Localhost verification should fail if the parameter is set to false

EDIT from @chatton 

Additional tasks to be completed after the internal audit:

- [x] Use allowed clients list to dynamically enable/disable and client type.
- [x] Add Unauthorized status for light clients. This status should be returned if the client type is not in the allowed_list
- [x] Add light client status checks in ChanOpenInit and ConnOpenInit.

**Comment by colin-axner** [comment]
There already is a parameter, clsoing

**Comment by colin-axner** [comment]
One possible approach: 
- add a enable/disable field to client state
- add msg to change this value (gov v1 msg, authority is only gov module) 
- update localhost client state upon execution
- use client state field in `Status`

**Comment by damiannolan** [comment]
I think in order to do gov v1 message execution it will incur an API breaking change to the ibc core `NewKeeper()` function. 

SDK modules which have migrated to use self managed params now take the additional arg to `NewKeeper()` functions: `authority` and store it as a field on the keeper.

[See here](https://github.com/cosmos/cosmos-sdk/blob/main/x/auth/keeper/keeper.go#L69) and below where the additional `authority` arg is added

**Comment by colin-axner** [comment]
Could we preemptively get the API breaking change in v7? Or does it feel too late in the cycle for that?

**Comment by damiannolan** [comment]
Sounds good to me. I think if its just changing the core `NewKeeper` function to accept an additional arg and store it as a field on the keeper then its totally fine

**Comment by chatton** [comment]
closing this as #3196 has been merged into the feature branch.
