### ISSUE TITLE
ICS24 Spec inconsistencies and improvements

### ISSUE THREAD

**Issue by ebuchman** [cosmos/ibc-go#28]
Surfaced from Informal Systems IBC Audit

## Summary of Bug

The path space laid out in the [ICS24 spec](https://github.com/cosmos/ics/tree/master/spec/ics-024-host-requirements#path-space) doesn't fully match the [ics24 code](https://github.com/cosmos/cosmos-sdk/blob/master/x/ibc/core/24-host/keys.go). It also might be helpful if each path in the spec had a name (which could correspond to function names in the code), and if the code was a bit more clearly organized for direct comparison with the spec.

Presumably things to fix in the spec:
- clientType from spec is missing in code (it's part of ClientState, so doesn't have its own path in store)
- `commitments/ports/{identifier}/channels/{identifier}/packets/{sequence}` in the spec is `commitments/ports/{identifier}/channels/{identifier}/sequences/{sequence}` in the code (and same for the `receipts/` and `acks/` paths.
- `ChannelCapabilityPath` in the code is missing from the spec  

There's also some redundancy in the code with prefix functions, like `PacketAcknowledgementPath` could use `PacketAcknowledgementPrefixPath` and `FullConsensusStatePath` could use `ConsensusStatePath`.

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
> clientType from spec is missing in code (it's part of ClientState, so doesn't have its own path in store)

The `ClientType` path was removed in the specs in [this PR](https://github.com/cosmos/ibc/pull/956).

> `commitments/ports/{identifier}/channels/{identifier}/packets/{sequence}` in the spec is `commitments/ports/{identifier}/channels/{identifier}/sequences/{sequence}` in the code (and same for the `receipts/` and `acks/` paths.

The paths now match between spec and implementation.

The [`channelCapabilityPath` exists in the specs](https://github.com/cosmos/ibc/blob/0da326fbedfd2c96aad807ed25e6eafd1399db07/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L204), although it doesn't match the path used in ibc-go (but it doesn't matter since it doesn't need to be proved by the counterparty).

> `PathValidator` is just a `NewPathValidator` with a noOp `idValidator` arg

I can't find the `PathValidator` function, so I guess this doesn't apply anymore.

So the only thing left would be splitting the `...Key` and `...Path` functions into different files. I will open a PR for this; if the team doesn't agree with the change, I will the just close the issue.
