### ISSUE TITLE
deps: use cosmos/ics23 v0.9.0

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2863]
- Remove replace tag to ics23 in Cosmos SDK.
- Backport to v2.4.x, v2.5.x, v3.3.x, v.3.4.x, v4.1.x, v4.2.x, v5.2.x (v5.0.x and v5.1.x will be discontinued when v5.2.0 is released) and v6.0.x.

**Comment by colin-axner** [comment]
I think we need to verify v0.9.0 is not API breaking for us. The go module name changed

**Comment by tac0turtle** [comment]
nothing broke from 0.8 to 0.9. remove the replace tag and after go getting it will work as is. this was the point of 0.9

**Comment by colin-axner** [comment]
Won't imports change? I believe anyone who calls [`ibctm.NewClientState(...)`](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/client_state.go#L25) will not be able to update to a new version of ibc-go without also changing their code to utilize `cosmos/ics23` instead of `confio/ics23`?

**Comment by tac0turtle** [comment]
no its still confio.ics23

**Comment by colin-axner** [comment]
Ah yea I see now. Nice!
