### ISSUE TITLE
rename `any` to `protoAny` across the codebase

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2890]
## Summary

see [comment thread](https://github.com/cosmos/ibc-go/pull/2824/files#r1040714332)

Rename `any` variables to `protoAny`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by RegisGraptin** [comment]
Hello, 

I have made some modification to change the variable names from `any` to `protoAny`.
I only modify the variable names when they were assigned by the functions `codectypes.NewAnyWithValue()` or `clienttypes.PackClientState()` as changed in the previous merge.
I do not know if other parts of the code needed to be changed ? Nor the documentation ? 

I created a fork that you can see here: https://github.com/RegisGraptin/ibc-go

Please let me know if I need to make some changes. 

Best regards

**Comment by crodriguezvega** [comment]
Thank you for working on this, @RegisGraptin! 

Maybe you can open a draft PR to `main` and we can already have a look at your changes and suggest any further improvements if needed? 

One request from our side for the future: next time you would like to contribute to the repository we would advice that you signal your intention on the issue that you would like to pick up, so that we can assign it to you and then it's also visible to the rest of the community that issue is taken and we avoid the possibility of multiple people working on the same issue at the same time. Thank you in advance!

**Comment by RegisGraptin** [comment]
Hello @crodriguezvega 

Thanks for your reply.
Yes, I will make a draft PR. 
And yes, I will remember it for the future, it's just that I wasn't sure to work on it completely.
