### ISSUE TITLE
Support json tx encoding for interchain accounts

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#3246]
## Summary

Currently interchain accounts only has protobuf encoding, json encoding would give more flexibility to using the feature, particularly for CosmWasm and Solidity smart contracts.

## Problem Definition

Adding json encoding would improve ICA composability, the feature is currently limited to only protobuf encoding

## Proposal

Add json encoding for ICA messages
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Is there an example user flow? Trying to understand whether this is a helper function or for decoding on the host? I'm not sure I follow when this would need to be rlp encoded on the host side within ibc-go

**Comment by colin-axner** [comment]
Revisiting, here's how to implement this issue for json. Please implement json and rlp support in separate prs. 

### User flow
json_encode(tx) -> give to controller -> ibc send, relay -> host recv -> decode_json(tx) into []sdk.Msg -> execute tx

json_encoding code will be external to ibc-go (potentially a wasm contract)

### Implementation

Add `EncodingJSON` to [metadata.go](https://github.com/cosmos/ibc-go/blob/ae27fa5960d523e4476776308ecd0b4cd3377671/modules/apps/27-interchain-accounts/types/metadata.go#L12) in the same format as `EncodingProtobuf`

Add `EncodingJSON` to the list of supported [encodings](https://github.com/cosmos/ibc-go/blob/ae27fa5960d523e4476776308ecd0b4cd3377671/modules/apps/27-interchain-accounts/types/metadata.go#L144)

Modify `SerializeCosmosTx`/`DeserializeCosmosTx` to take in the full interchain accounts packet data. It should switch on the encoding type, something similar to:

```go
// DeserializeCosmosTx, pass in full packetData
// *codec.ProtoCodec implements the JSONCodec interface

if _, ok := cdc.(*codec.ProtoCodec); !ok {
        return nil, errorsmod.Wrap(ErrInvalidCodec, "provided codec is not of type %T", codec.ProtoCodec{})
}

var cosmosTx CosmosTx

switch packetData.Encoding
case EncodingProtobuf:
    if err := cdc.Unmarshal(data, &cosmosTx); err != nil {
        return nil, err
    }
    
case EncodingJSON:
    if err := cdc.UnmarshalJSON(data, &cosmosTx); err != nil {
        return nil, err
    }
    
default:
    return nil, errorsmod.Wrap(ErrUnsupportedEncoding, "encoding type %s is not supported", packetData.Encoding)
}
```

Similar changes can be made to `SerializeCosmosTx`

### Testing

A test should be added to the host submodule which creates a channel using the JSON encoding. It should send a successful json encoded transaction (succeeds) and it should send a proto encoded transaction (fails). An e2e is not necessary in my opinion. 

It would be greatly appreciated if someone could test this integration with wasm :pray: 

I may have missed something so please ask questions if you run into any issues

**Comment by crodriguezvega** [comment]
Thanks for the write-up, @colin-axner! I would like to add a couple of things and hear your opinion.

I think instead of passing the full [`InterchainAccountPacketData`](https://github.com/cosmos/ibc-go/blob/3849b0f5cdebcb1f0cb2179e375a586f5c9dcd8d/modules/apps/27-interchain-accounts/types/packet.pb.go#L57) to `SerializeCosmosTx`/`DeserializeCosmosTx` we should just add an extra argument with the type of encoding. The interchain account packet data doesn't contain any information about the format used to encode the data. However, doing this (well, actually either taking the full packet data or adding an extra argument for encoding type) will break the API of these public functions, right?

Maybe we can also make the encoding type an enum, at least in the Go code, but still use [a string in the `Metadata` type](https://github.com/cosmos/ibc-go/blob/3849b0f5cdebcb1f0cb2179e375a586f5c9dcd8d/modules/apps/27-interchain-accounts/types/metadata.pb.go#L38), so that we don't break the API here as well. 

We also have [this helper CLI command on the host submodule to generate the packet data](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/host/client/cli/tx.go#L21) that I think we should also adapt so that it takes an extra parameter for the encoding type.

**Comment by webmaster128** [comment]
Please note that there is no specification for how Cosmos SDK transactions are serialized to JSON. It is defined by the Cosmos SDK implementation based on the protobuf JSON specs plus a bunch of extra rules that may or may not be consistent. I.e. the JSON serialization can change any time. I would not recommend to assume chain 1 and chain 2 use the same JSON codec as long as such a spec does not exist.

**Comment by aaronc** [comment]
> Please note that there is no specification for how Cosmos SDK transactions are serialized to JSON. It is defined by the Cosmos SDK implementation based on the protobuf JSON specs plus a bunch of extra rules that may or may not be consistent. I.e. the JSON serialization can change any time. I would not recommend to assume chain 1 and chain 2 use the same JSON codec as long as such a spec does not exist.

The SDK does not apply any extra rules to proto JSON serialization. The only deviation that might be present relates to how some legacy amino types marshal json which I would basically consider bugs at this point. We attempt to follow the official proto3 spec to the letter, but of course that spec could change. Also in the future we will use the official protoreflect based JSON serializer so there should be no legacy amino glitches with that

**Comment by webmaster128** [comment]
I would love to see see this become a reality. It would help independent implementations so much. But right now I often see JSON seralizations that differ from proto. E.g. the Dec cases which are integer string on the protobuf level but in JSON suddenly have a decimal point. Also embedded CosmWasm messages are bytes at protobuf level but nested objects in JSON. Is this something you consider bugs and everything should be the original protobuf JSON? What about the protobuf option system? Should it allow changes to the JSON representation or should it all become the standard once we don't need Amino JSON anymore?

**Comment by colin-axner** [comment]
Thanks everyone for the context. I have some clarifying questions just to make sure I follow the concerns being raised here. Please let me know if I have misunderstood something

As @webmaster128 points out in the first https://github.com/cosmos/ibc-go/issues/3246#issuecomment-1503171199, the SDK does not contain json schema's for every sdk.Msg nor does it enforce this practice. Instead it relies on the [protobuf json](https://protobuf.dev/programming-guides/proto3/#json) mapping which as @aaronc mentions could technically change from under our feet (the official serializer reserving the right to making breaking changes). 

I'm not sure I follow the followup https://github.com/cosmos/ibc-go/issues/3246#issuecomment-1509318456 though? This seems to be pointing out differences between proto and JSON, not proto JSON vs JSON?

With ICA, the primary concern is ensuring that we can decode a msg type using the encoding type negotiated at channel opening (in addition to support encoding types that connecting controllers have access to). 

What is the exact concern with the lack of a specification for encoding sdk.Msgs? Is it a concern that the proto json mapping could potentially change (ie future proofing)? Is it a concern that without json schema's attached to sdk.Msg type, it is difficult for smart contract users to correctly encode a specific sdk.Msg? Please note that ICA will be expecting an Any which references to specific sdk.Msg implementation.

While no json schema explicitly exists, it does implicitly exist by referencing the proto definition + using proto json.

**Comment by colin-axner** [comment]
Hi @aaronc and @webmaster128, there are two proposed implementations for this issue, #3725 and #3796. If you have any further comments, they would be very much appreciated! 

In further consideration, I'm not so sure we need to worry about proto JSON future compatibility only with respect to ICA transaction encode/decode. IBC packet data (such as for transfer and ICA) is already encoded/decoded using proto JSON and will be required to maintain backwards compatibility in the absence of a coordinated upgrade between both channel ends. Thus in such a world where this compatibility would break, we would need to go the extra mile regardless to ensure we maintain compatibility

**Comment by colin-axner** [comment]
Cool so I looked into this some more, documenting my findings here. 

The purpose of this feature is to support:

wasm contracts to json encode SDK msgs -> which are relayed to another chain -> and decoded by ibc-go ica host module into sdk.Msg and then the msgs are executed via baseapp

One issue I don't see how we can get around is usage of `Any`s. This is because the wasm contract can send the ibc-go ica host any `sdk.Msg`, thus when the ica host module receives a `Tx`, it needs to figure out how to decode the msgs. Thus, the encoded bytes need to include self referential information (type url) so that it can look up how to decode this type so that it can be executed and routed to the correct handler. This is the purpose of the `Any` type, so while you could do some work around to replicate the same behaviour via the standard json encoding library, in the end you are performing the same tasks as a proto3 library

From what I've been able to tell, proto3 json differs from the standard json library in a few ways:
- int64/uint64 are encoded as strings
- enums are encoded as strings
- handles `Any` type (see below quote)

> If the Any contains a value that has a special JSON mapping, it will be converted as follows: {"@type": xxx, "value": yyy}. Otherwise, the value will be converted into a JSON object, and the "@type" field will be inserted to indicate the actual data type.

[proto3 json spec ref](https://github.com/golang/protobuf/commit/67cbcadfc96f21404e1d5ef40e7f3b35b0a073c5#diff-c01cbfcb28e2142a216b1b5722cc68ba71b9f5e57b3e3370c76b656a1653bd64R36)

[impl ref](https://github.com/golang/protobuf/commit/67cbcadfc96f21404e1d5ef40e7f3b35b0a073c5#diff-c01cbfcb28e2142a216b1b5722cc68ba71b9f5e57b3e3370c76b656a1653bd64R36)

I did some testing and it appears to me the pbjson impl can successfully unmarshal any bytes encoded by the standard json library. The reverse is not true. If you encode using proto3 json (say by using a string for a int64) the standard library will return an error

Based on this understanding, if a new encoding type is added for `Proto3JSON`, what this is specifying in terms of requirements for contracts, is that they encode their `Any`s using the format defined in the proto3 spec. They should also encode the other types (int64, uint64, enums) in the same way, but my investigation suggests that it should not cause an error if the equivalent of the standard json library is used. 

The requirements set by the proto3 json spec for `Any`s seems reasonable to me. It clearly differentiates it as a special type and as @srdtrk has shown, there is not much overhead in the contract code to give it the special "@type" tag. In my opinion, if the handling of the `Any` changed, it would be the equivalent of a new `EncodingType` from the interchain account perspective and thus channel upgradeablility could be used to change the encoding expectations, but I would be very surprised if that standard ever changed 

As a side note:
- transfer uses json encoding for packet data
- ica uses proto3 json (due to the enum type)

From my understanding based on @srdtrk research, the [rust json library](https://docs.rs/serde_json/latest/serde_json/) provides good flexibility in determining exactly how to encode a custom type. As shown in some code @srdtrk sent me, meeting the proto3 requirement is quite simple with the standard rust library:

```rust
#[derive(Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum CosmosMessages {
    MsgSubmitProposalV1 {
        #[serde(rename = "@type")]
        type_url: String,
        content: Box<CosmosMessages>,
        initial_deposit: Vec<Coin>,
        proposer: String,
    },
    TextProposal {
        #[serde(rename = "@type")]
        type_url: String,
        title: String,
        description: String,
    },
}

#[derive(Serialize, Deserialize)]
pub struct CosmosTx {
    pub messages: Vec<CosmosMessages>,
}
```

Based on these findings, adding a `Proto3JSON` encoding type seems sufficiently safe in terms of future compatibility and meets to need for contract developers to easily encode ICA transactions with json. In addition it allows us to use well established proto3 libraries instead of implementing custom handling for types the standard json encoder cannot handle (`Any` in this case)

Please let us know if you have any concerns or comments, we will likely be moving forward with #3796 (excellent work @srdtrk)

**Comment by srdtrk** [comment]
I'll note that PR [#3796](https://github.com/cosmos/ibc-go/pull/3796) is end to end tested using this [CosmWasm implementation of the ica controller](https://github.com/srdtrk/cw-ica-controller/) and the e2e testing package in that repo. I've verified that the json codec we used in this PR and cosmwasm communicate as intended.
