### ISSUE TITLE
Add handling of channel upgrades to ADR 008

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3318]
## Summary

Once ibc-go supports upgrading channels, logic on how this should be handled/supported by ADR 008 implementations should be added to the ADR itself. 

see [comment](https://github.com/cosmos/ibc-go/pull/1976#discussion_r1142030135)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
I think we can close this issue, because when it was created the ADR had an `IBCActor` interface with channel handshake callbacks, but that interface was later removed and the `ContractKeeper` interface that we have now only has entry points for the packet callbacks. I will close it now, we can re-open if I am wrong in my reasoning.
