### ISSUE TITLE
header failed basic validation

### ISSUE THREAD

**Issue by Sirius198** [cosmos/ibc-go#3409]
```
~/.relayer/config$ ibc-setup connect -v

verbose: Queried unbonding period {"seconds":1814400}
verbose: Create Tendermint client
verbose: Queried unbonding period {"seconds":1209600}
verbose: Create Tendermint client
info: Connection open init: 07-tendermint-3 => 07-tendermint-2712
verbose: Get latest commit
verbose: Get validator set for height 653
verbose: Get header for height 653
verbose: Get validator set for height 649
verbose: Get header for height 649
verbose: Update Tendermint client 07-tendermint-2712
info: Connection open try: 07-tendermint-2712 => 07-tendermint-3 (connection-3)
verbose: Get latest commit
verbose: Get validator set for height 9030556
verbose: Get header for height 9030556
verbose: Get validator set for height 9030550
verbose: Get header for height 9030550
verbose: Update Tendermint client 07-tendermint-3
error: Query failed with (6): rpc error: code = Unknown desc = header failed basic validation: commit signs block 038A8AEFD65C5D0024A1F5BFA851628516FE8FCA3F51D804C3C3C1392778F698, header is block 2A3106AEB1EABA15647C4EFB4F29A03A1270E2D08E603D4C73CA73DD9C2C6D01 [cosmos/ibc-go/v4@v4.3.0/modules/light-clients/07-tendermint/types/header.go:62] With gas wanted: '0' and gas used: '6666' : unknown request
```

What's this error: `header failed basic validation`?

**Comment by crodriguezvega** [comment]
The underlying error is coming from CometBFT [here](https://github.com/cometbft/cometbft/blob/main/types/light.go#L152-L154). There's a mismatch between the Merkle root hash of all the fields in the header and the hash in the block ID of the commit. See the [`SignedHeader` struct documentation in CometBFT](https://github.com/cometbft/cometbft/blob/main/spec/core/data_structures.md#signedheader) for more information.

I will close the issue now since there's no action we need to take for ibc-go, feel free to comment if you have any more questions. For the future, we would appreciate if general questions are asked [on Discord ](https://discord.gg/CMfYR4Ny)or in the Q&A section of [this repo's Discussions](https://github.com/cosmos/ibc-go/discussions/categories/q-a), then the answer will also be visible for other people as well. Thanks!
