### ISSUE TITLE
Consider using a linter for markdown files

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3543]
## Summary

It can be useful to lint our markdown files for consistency. Adding this tooling into our workflow would prevent reviewing unnecessary diffs when a linter is run on the markdown files. 

see related [comment thread](https://github.com/cosmos/ibc-go/pull/3511#discussion_r1178936812)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
We do already have a `docs-lint` rule in the [Makefile](https://github.com/cosmos/ibc-go/blob/48341b40d96f8978cd072ed3059aa887afacc40c/Makefile#L307) and its a suggestion in the [Development Setup](https://github.com/cosmos/ibc-go/blob/main/docs/dev/development-setup.md#documentation).

**Comment by colin-axner** [comment]
Should we add this to our ci checks?

**Comment by DimitrisJim** [comment]
we should ask @damiannolan since we know how much love he has for linters complaining to him.

**Comment by damiannolan** [comment]
We have `make docs-lint` and `make docs-lint-changed`, both of which use this `markdownlint` tool afaik. 

IMO adding a CI check for this might be a little overkill, especially since we're already pushing limits on GH runners. We could enforce a pre-commit hook, I think @chatton already uses one in his local setup which makes use of `docs-lint-changed` as well as `lint-fix-changed` (for golangci-lint)

**Comment by DimitrisJim** [comment]
> IMO adding a CI check for this might be a little overkill, especially since we're already pushing limits on GH runners

Can't we set it to only run when changes to `docs/` are triggered?

**Comment by damiannolan** [comment]
Yeah true

**Comment by srdtrk** [comment]
Most files are already linted. The real issue is that we don't have a custom ruleset for our project. Markdown linter's default settings will result in markdown files that reflect the author's preferred markdown authoring preferences. This is what causes in-consistency in our docs. I think we can rename this issue to something like `Define custom markdownlint ruleset configuration`

**Comment by DimitrisJim** [comment]
do we not have [`.markdownlint.jsonc`](https://github.com/cosmos/ibc-go/blob/main/.markdownlint.jsonc) for the rules? The idea of the issue as I understood it is to have markdownlint run on new changes to guarantee consistency.

**Comment by srdtrk** [comment]
We do @DimitrisJim, however, it is not customised enough. It just tells the linter to ignore some settings. Currently the style settings are still set to default. This includes things like heading style, indentations, unordered list style and more. For example, the fix to the comment thread @colin-axner linked in this issue would be to add

```json
  "MD004": {
    "style": "dash"
  },
```

This is why Colin noticed some files being changed `*` =>  `-` and others `-` => `*` by the linter.

**Comment by srdtrk** [comment]
I'm addressing this issue in the next docs PR

**Comment by srdtrk** [comment]
I've factored this out of the docs PR, and instead, linter/workflow related changes will have their own PR

**Comment by crodriguezvega** [comment]
Closed by #3805
