### ISSUE TITLE
Add ability to fast forward upgrade sequence when counterparty is ahead on Try step

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#3794]
## Summary

On the UpgradeTry step, if the counterparty sequence is ahead, allow the self upgrade sequence to be fast forwarded. Note, the counterparty upgrade sequence needs to be verified before performing state changes that won't get reverted. So when implementing this feature, we need to ensure that if an invalid counterparty sequence is provided, our upgrade sequence is not incremented when the transaction completes.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Just a note: the [TODO in the code](https://github.com/cosmos/ibc-go/blob/c249e1e3bdf0ae28f1b3c221ebce9787a60bf114/modules/core/04-channel/keeper/upgrade.go#L130) is after the [call to `ChanUpgradeInit`](https://github.com/cosmos/ibc-go/blob/c249e1e3bdf0ae28f1b3c221ebce9787a60bf114/modules/core/04-channel/keeper/upgrade.go#L125), but I believe the fast forwarding should happen before, since [`ChanUpgradeInit` increments the upgrade sequence](https://github.com/cosmos/ibc-go/blob/c249e1e3bdf0ae28f1b3c221ebce9787a60bf114/modules/core/04-channel/keeper/upgrade.go#L46). That also how the spec is written:

```typescript
if counterpartyUpgradeSequence > currentChannel.upgradeSequence {
  currentChannel.upgradeSequence = counterpartyUpgradeSequence - 1
}

initUpgradeChannelHandshake(portIdentifier, channelIdentifier, upgradeFields, counterpartyUpgrade.timeout)
```

**Comment by charleenfei** [comment]
i think it's actually more readable to do it after `ChanUpgradeInit`, because we only want to fast forward our upgrade sequence if the counterparty's upgrade sequence is still higher even after we've incremented ours. it results in the same upgrade sequence setting either way.
