### ISSUE TITLE
Make connection lookup calls consistent in 04-channel

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3840]
## Summary

The 04-channel submodule has inconsistent usage of `k.GetConnection()` and `k.connectionKeeper.GetConnection()` in order to lookup a `connectionEnd`.

[See thread](https://github.com/cosmos/ibc-go/pull/3828#discussion_r1228588878)

Make usage consistent across handshake and upgrade handlers.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by DimitrisJim** [comment]
Yeah, I see we wrap in the most recent usages of `GetConnection` (i.e in upgrade.go). I guess it isn't all that necessary really (and kinda beats the point of having `GetConnection` handle the error uniformly for us).

Personally, I don't mind using `channelKeeper.GetConnection` since it's there already.

**Comment by crodriguezvega** [comment]
We will use `k.connectionKeeper.GetConnection`.

**Comment by crodriguezvega** [comment]
Closed by #4146.
