### ISSUE TITLE
RegisterLegacyAminoCodec is unused in 29-fee (should be called in module.go)

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4104]
## Summary

`RegisterLegacyAminoCodec` is defined in 29-fee types but is not referenced in the `module.go` for 29-fee. I suspect ledger signing might not work (but untested accusation) 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
So the problem is that [this `RegisterLegacyAminoCodec` function](https://github.com/cosmos/ibc-go/blob/23eabb55bf2987c2bec3a132d9bab4c4b9e674fb/modules/apps/29-fee/types/codec.go#L12) is not called in [this other `RegisterLegacyAminoCodec` functions](https://github.com/cosmos/ibc-go/blob/23eabb55bf2987c2bec3a132d9bab4c4b9e674fb/modules/apps/29-fee/module.go#L48)?

@damiannolan you wanted to do some testing with a ledger for #4570, right? Would it be possible for you to check if @colin-axner's hypothesis is correct? If it doesn't work then we can open a quick PR to fix it.
