### ISSUE TITLE
Change `ErrInvalidConnectionState` to `ErrUnexpectedConnectionState`

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4149]
Change [`ErrInvalidConnectionState`](https://github.com/cosmos/ibc-go/blob/31b3c6000ca05be316d5bb49d34e073ed07a82e8/modules/core/03-connection/types/errors.go#L13) to `ErrUnexpectedConnectionState` with error message `unexpected connection state`.

**Comment by SurajAnand88** [comment]
Hey @crodriguezvega i want to work on this issue

**Comment by crodriguezvega** [comment]
Thank you, @SurajAnand88! I will assign the issue to you. :)

**Comment by DimitrisJim** [comment]
Similar considerations to https://github.com/cosmos/ibc-go/pull/4154#issuecomment-1645204038. Since these errors are heavily present in `upgrade`, would be shame to add to main and make the sync up of `04-channel-upgrades` to main more trouble than it already is.

I.e my vote is for either waiting until `04-channel-ugprades` is merged or pushing directly to that branch (preferable).

**Comment by SurajAnand88** [comment]
Hey @DimitrisJim 

Thank you for your input and insights regarding the PR and its potential impact on the `main` branch and the `04-channel-upgrades` branch.

Considering that these errors are heavily present in the upgrade process, it's crucial to ensure a smooth and seamless integration of changes into the `main` branch. I understand your concern about making the sync-up process more complicated if we push the changes directly to `main` at this point.

To maintain a cohesive codebase and avoid any potential conflicts, would it be possible for us to wait until the `04-channel-upgrades` branch is merged? This way, we can ensure that the changes are thoroughly tested and aligned with the ongoing development in that branch.

If the integration into `main` is not urgent, waiting for the `04-channel-upgrades` branch to be merged could provide a more stable foundation for our changes.

Please let me know your thoughts on this approach. If you believe that pushing directly to the `04-channel-upgrades` branch is preferable.

Looking forward to your response.

**Comment by DimitrisJim** [comment]
I wouldn't have much of an issue with the PR targeting 04-channel-ugprades, Ideally it could wait for the merge (and not be an additional PR someone has to review before the merge) but not too strong with that opinion since I think the change could be easily reviewable.

I.e if you're itching to contribute, go for it! Target 04-channel-upgrades and I'll definitely find some time to review it.

**Comment by SurajAnand88** [comment]
I think it's better to  wait for the 04-channel-upgrades branch to merge for a smoother process and avoid extra work for reviewers. I'll explore other contributions in the meantime. Once it's merged, I'll work on the changes and submit the PR.

**Comment by crodriguezvega** [comment]
I will close the issue, since we just decided to keep the name of the error as is.
