### ISSUE TITLE
Add checkForUpgradeCompatibility check in try handler

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4250]
## Summary

[Spec change](https://github.com/cosmos/ibc/pull/999/files#diff-69d7c4ac1d4cdeeabcc757d3a34e85945ebc5613a034a52ebd0769cd8a0fc560R526)

Add a call to [`checkForUpgradeCompatibility`](https://github.com/cosmos/ibc-go/blob/e00fb0fda1c3fce67a2e18656bef6f4f67577aed/modules/core/04-channel/keeper/upgrade.go#L735) [here](https://github.com/cosmos/ibc-go/blob/e00fb0fda1c3fce67a2e18656bef6f4f67577aed/modules/core/04-channel/keeper/upgrade.go#L156). If an error is returned,  return the normal error so the transaction fails. There will now be a duplicate check (another one in startFlushUpgradeHandshake, the latter check will be removed in a followup pr)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
There is actually an issue with the implementation in this PR and the one that has already been merged in #4285 

Currently, just moving the `checkForUpgradeCompatibility` is not enough, since there is actually some [logic](https://github.com/cosmos/ibc-go/blob/ce03b9953f25f6a3b14bd6af8c6bd509f2d1c2d6/modules/core/04-channel/keeper/upgrade.go#L737-L750) which potentially modifies the `channel.UpgradeSequence`. 

The actual effect this has is that on chain A, the channel upgrade sequence is written in `WriteChanUpgradeInit`, however by the time the new `checkForUpgradeCompatibility` happens on chain B, the upgrade sequence is not fast forwarded and is still zero.

I'm going to put this on hold in favour of some of the other ongoing refactors, but we need to reconsider this when we pick up work on this again.
