### ISSUE TITLE
Propagate ibc authority to 04-channel to be used within upgrade cancellation

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4420]
## Summary

The `authority` of the ibc module is required in order to do some privileged action when performing a cancellation of an upgrade.

We should determine how we want to access the `authority` from the 04-channel submodule, and other submodule if required in future. The `authority` currently exists as a field on the `IBCKeeper` and is exposed through the `GetAuthority` method. However, submodule keepers composed within the `IBCKeeper` cannot reach this.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Adding needs-discussion label so we can align on the approach here prior to completing the issue

**Comment by damiannolan** [comment]
After discussion, let's check `msg.Signer` against `k.GetAuthority` in the msg server handler and pass a bool to 04-channel in order to infer if it is an authorized upgrader or not. This decides whether or not proof verification is carried out

**Comment by charleenfei** [comment]
could we also pass the address of `k.GetAuthority` to the `UpgradeCancel` keeper function from the `msg_server`, rather than passing a bool? then we could use an `isAuthorised` function that checks the equality of the values, feels like this could be preferable than just passing a bool that would determine some fairly important logic?
