### ISSUE TITLE
App OnRecvPacket returns a failed ack, and all app events are lost

### ISSUE THREAD

**Issue by fx0x55** [cosmos/ibc-go#4520]
## Summary of Bug

when an error is processed by the OnRecvPacket method, it is displayed as an event

https://github.com/cosmos/ibc-go/blob/7418969fa953c6d74501741c84ee7105a9d8fc0c/modules/apps/transfer/ibc_module.go#L213-L215

but after [this](https://github.com/cosmos/ibc-go/commit/4973957900d70969d99371e6ed24c47400f5abe6) commit,  the event is lost

## Expected Behaviour

Restore an error event or modify the way errors are displayed, for example by acknowledgement_error

## Version

- release/5.x
- release/6.x
- release/7.x
- main

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thanks for opening this issue, @fx0x55. Unfortunately there is not easy, straight forward way to fix this at the moment. [Returning the error information in the acknowledgement](https://github.com/cosmos/ibc-go/pull/4749) is also not an option, since that would lead to non-deterministic error messages if the error strings ever change. 

The concrete error is logged on the host [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/host/ibc_module.go#L128) and the logs include `"module": "x/ibc-interchainaccounts"`, so it should be easy to find them.

Is using the logs for debugging the error a viable alternative for you for the time being?

**Comment by fx0x55** [comment]
Thanks for your answer
