### ISSUE TITLE
Grant read access to substitute store and write access to subject store

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4547]
_Surfaced from Interchain IBC team's review of 08-wasm at hash https://github.com/strangelove-ventures/ibc-go/commit/96e9930ab87a171a3ae6ac9717ee25bfda77212b_

### Proposal

We could remove [`subjectPrefix` and `substitutePrefix` from `updateProposalWrappedStore`](https://github.com/cosmos/ibc-go/blob/1425ca203949c5482149d57a98ec5e33bb8e3ea3/modules/light-clients/08-wasm/types/store.go#L21-L22) and when light client contracts call `Get` the implementation only allows read access to the substitute store, and when the light client contracts call `Set` the implementation only allows write access to the subject store:

```golang
func (ws updateProposalWrappedStore) Get(key []byte) []byte {
  return ws.substituteStore.Get(key)
}

func (ws updateProposalWrappedStore) Set(key, value []byte) {
  ws.subjectStore.Set(key, value)
}
```

This would require changes in the contracts.

**Comment by DimitrisJim** [comment]
From eng.call: Keep subject/substitute prefixes but only allow reads on `substitute` and writes on `subject`.

**Comment by DimitrisJim** [comment]
Scope has changed after some discussion. We will allow reads from both subject and substitute but writes only to the subject. Reading from both allows the most flexibility for contracts while we couldn't see much rationale for allowing writes to substitute.

Prefixes as they originally existed will still be used by prepending them to a given key to be looked up. This should be clearly documented.

This doesn't break the contract API in any way since the contracts have originally been written to use the prefixes.

**Comment by DimitrisJim** [comment]
done in #4898
