### ISSUE TITLE
Remove InitModule function in interchain accounts

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#4639]
## Summary

The `InitModule` function was added in interchain accounts as an alternative to InitGenesis during in place upgrades to allow app developers to set their custom params. However, the same logic can be achieved by setting the desired params directly after calling `mm.RunMigrations`, we should remove the `InitModule` function and update docs to indicate this behaviour. 

This should ease ica integration as no custom init function needs to be called and it eases our maintence burden as there is no longer a function mimicing InitGenesis  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
💯

**Comment by muku314115** [comment]
Should this be recorded in the v7.3.x migration docs directly?

**Comment by crodriguezvega** [comment]
> Should this be recorded in the v7.3.x migration docs directly?

I don't think we should back port this change to v7.3.x, since a function that is part of the public API is removed, so that would be an API-breaking change. Therefore, mostly likely this change will be released in v9, so you could add a `v8-to-v9.md` migration file already, if you would like to. Otherwise we can do document this in the v9 migration docs ourselves later on.
