### ISSUE TITLE
Implement `MigrateContract` RPC endpoint

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#4925]
Pre-requisite:
- [x] https://github.com/cosmos/ibc-go/issues/4928

This endpoint will be used for migrating a light client contract to a new wasm byte code.

We will have a new message (e.g. `MsgMigrateContract`) and RPC endpoint (e.g. `MigrateContract`). `MsgMigrateContract` could have the following fields:

- Client ID (for the contract instance that that should be migrated to the new wasm code).
- Code hash (of the wasm code the contract will be migrated to).
- [A `msg` field with the bytes that can be passed to the contract at migration](https://github.com/CosmWasm/wasmd/blob/894076a25cb2ff5219486e3d3628a5dd982e7ac6/proto/cosmwasm/wasm/v1/tx.proto#L217), even if we don't use it right now.

We don't need to have a field for the code hash of the contract we migrate from, since we have the client ID. 

Depending on https://github.com/cosmos/ibc-go/issues/4928 we use the client ID as the contract address, or we use the client ID to access the client store and retrieve the contract address. hat we need to use in the call to `wasmVM.Migrate`.

In `MigrateContract`:

- We check that the new code hash is in the list of allowed code hashes. Since this RPC endpoint is in 08-wasm, we have access to the module store and we can do this check.
- If the old and new code hashes are the same, then we can exit early.
- We call `wasmVM.Migrate` with the contract address ([either the client ID or the contract address stored in the client-prefixed store](https://github.com/cosmos/ibc-go/issues/4928)) and the new code hash.
- We update the code hash in the client state.

We need to update the contracts to add the migrate endpoint to them, even if they no-op at the moment.

**Comment by crodriguezvega** [comment]
I just opened this (draft) PR to add the migrate entry point to the contracts. I kept it simple for now and the entry point just no ops. However, I have a question: I had to add a `MigrateMsg` struct, which is also empty for now, but I guess whenever we want to call `wasmVM.Migrate` with the json-encoding bytes of message, they should deserialise into the `MigrateMsg` struct, right? Does that mean that we need to define already want information we would need to include in `MigrateMsg` in case we want to migrate a contract? Otherwise, if the contract is deployed but we realise later on that we need specific information, then we cannot pass it because it will not serialised correctly, right? 

Any thoughts, @srdtrk?

**Comment by srdtrk** [comment]
@crodriguezvega I don't think we should add this to centauri contracts. They can add this when they need it. A contract need not have any `migrate` entry point. In fact, the first version of a contract is expected not to have it.

Contracts may use a migrate entry point once they are meant to replace another contract. Or after some semver version. [Here is an example how one might look like](https://github.com/srdtrk/cw-ica-controller/blob/main/src/contract.rs#L78-L88).

In my opinion, if we wanna test `migrate`, we should construct a new dummy contract with a migrate entry point. This is not as hard as it sounds because we can just use a contract that doesn't do anything on sudo but only does something in migrate. Lmk what you think

**Comment by crodriguezvega** [comment]
Ok, cool. Thanks, @srdtrk. Then I will close the PR adding the migrate endpoint. 

Yes, let's create a dummy contract to test migration e2e. I had opened [this issue](https://github.com/cosmos/ibc-go/issues/4971) for it.
