### ISSUE TITLE
Question about function OnAcknowledgementPacket in apps/transfer/keeper/relay.go

### ISSUE THREAD

**Issue by michwqy** [cosmos/ibc-go#5135]
I find that in [ibc-go](https://github.com/cosmos/ibc-go/blob/336bf2c4b52b5d9152e44df89139543978745fdd/modules/apps/transfer/keeper/relay.go#L316C16-L316C40), when the acknowledgement error, the tokens will be refunded.
```typescript
func (k Keeper) OnAcknowledgementPacket(ctx sdk.Context, packet channeltypes.Packet, data types.FungibleTokenPacketData, ack channeltypes.Acknowledgement) error {
	switch ack.Response.(type) {
	case *channeltypes.Acknowledgement_Error:
		return k.refundPacketToken(ctx, packet, data)
	default:
		// the acknowledgement succeeded on the receiving chain so nothing
		// needs to be executed and no error needs to be returned
		return nil
	}
}
```
But in IBC Spec [ICS-20](https://github.com/cosmos/ibc/blob/main/spec/app/ics-020-fungible-token-transfer/README.md), when the acknowledgement is not successful, the tokens will be refunded.
```typescript
function onAcknowledgePacket(
  packet: Packet,
  acknowledgement: bytes) {
  // if the transfer failed, refund the tokens
  if (!acknowledgement.success)
    refundTokens(packet)
}
```
Is this a special design? Is there any difference?

**Comment by crodriguezvega** [comment]
Thank you for bringing your question, @michwqy. As Aditya replied to your question in the spec repository, the spec should check that the acknowledgement is not of the error type. There was recently a situation where an IBC implementation checked explicitly for the string `AQ==` in the acknowledgement and that caused some successful acknowledgements to be misinterpreted as error acknowledgements because they didn't match that format (see the details [here](https://composablefi.medium.com/security-disclosure-and-retrospective-analysis-510c17c6618e)). I will close the issue now, I hope your question is answered.

I see that you're working on TLA+ models for IBC. Do you mind me asking what your goal is?

**Comment by michwqy** [comment]
Thanks for you reply, @crodriguezvega . I am a student learning how to apply model checking to blockchain. I will analyze some parts of the IBC protocol based on my time and ability.

**Comment by crodriguezvega** [comment]
> Thanks for you reply, @crodriguezvega . I am a student learning how to apply model checking to blockchain. I will analyze some parts of the IBC protocol based on my time and ability.

Ah, that's great. You've been asking very good questions about the protocol, so keep them coming. :)
