### ISSUE TITLE
ICA host packet failure events not being emitted

### ISSUE THREAD

**Issue by dferendo** [cosmos/ibc-go#5284]
## Summary of Bug

When a controller sends a packet to a host and the packet fails, the controller receives ["error handling packet: see events for details"](https://github.com/cosmos/ibc-go/tree/v8.0.0/modules/core/04-channel/types/acknowledgement.go#L16). When using the query `binaryd q interchain-accounts host packet-events` on the host chain, the event is not found. 

Digging deeper, in [msg_server.go](https://github.com/cosmos/ibc-go/blob/v8.0.0/modules/core/keeper/msg_server.go#L488), a cache context is created:  

```
	// Perform application logic callback
	//
	// Cache context so that we may discard state changes from callback if the acknowledgement is unsuccessful.
	cacheCtx, writeFn = ctx.CacheContext()
	ack := cbs.OnRecvPacket(cacheCtx, msg.Packet, relayer)
	if ack == nil || ack.Success() {
		// write application state changes for asynchronous and successful acknowledgements
		writeFn()
	}
```

The host [OnRecvPacket](https://github.com/cosmos/ibc-go/blob/v8.0.0/modules/apps/27-interchain-accounts/host/ibc_module.go#L113) is called and emits an event regardless successful or not:

```
	// Emit an event indicating a successful or failed acknowledgement.
	keeper.EmitAcknowledgementEvent(ctx, packet, ack, err)
````

Circling back to [msg_server.go](https://github.com/cosmos/ibc-go/blob/v8.0.0/modules/core/keeper/msg_server.go#L488), when the ack is not successful nothing is saved to the state thus the events submitted in OnRecvPacket are discarded. 

Issue #4173 can also be closed by fixing this bug and creating the e2e test. Possible solution is to add the events to the main context.

## Expected Behaviour

Events are emitted when ICA host packages fail

## Version

v8.0.0

## Steps to Reproduce

Emitting events in the [mocked ibc module](https://github.com/cosmos/ibc-go/blob/v8.0.0/testing/mock/ibc_module.go#L125) and checking if events are emitted in [msg_server_test](https://github.com/cosmos/ibc-go/blob/v8.0.0/modules/core/keeper/msg_server_test.go#L33) should reproduce this issue.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by migueldingli1997** [comment]
Hey @srdtrk @damiannolan 👋 I see you've acknowledged the issue, thanks for this. I'm wondering if we could discuss a potential solution to this. I imagine emitting all of the events regardless of the `ack` success is not the way to go, since we do not want to emit events related to state changes that will not be applied. I also imagine that changing the `OnRecvPacket` function signature would cause unnecessary issues for any user/code that relies on this function.

Perhaps a reasonable start would just be to add logging at the event emission so that node operators can at least get an indication of what went wrong?

**Comment by crodriguezvega** [comment]
Hi @migueldingli1997. Thanks for opening the issue. The event used to be emitted, but had to be removed to [address the Huckleberry security advisory](https://github.com/cosmos/ibc-go/commit/4973957900d70969d99371e6ed24c47400f5abe6). Unfortunately there is not easy, straight forward way to fix this at the moment. [Returning the error information in the acknowledgement](https://github.com/cosmos/ibc-go/pull/4749) is also not an option, since that would lead to non-deterministic error messages if the error strings ever change. 

The concrete error is logged on the host [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/host/ibc_module.go#L128) and the logs include `"module": "x/ibc-interchainaccounts"`, so it should be easy to find them. Is using the logs for debugging the error a viable alternative for you for the time being?

Several teams have already raised this problem and we will try to find a solution (probably will require collaboration with the SDK team), most likely at the beginning of the new year.

**Comment by srdtrk** [comment]
Wouldn't the log be discarded as well since we are only logging the events in the discarded cached context @crodriguezvega ?

**Comment by puneet2019** [comment]
https://github.com/cosmos/ibc-go/issues/3390#issuecomment-1866042167 i guess i commented on the wrong issue

**Comment by chatton** [comment]
@srdtrk is the behaviour of the logger that it will write the log lines on the `writeFn` function? I would have assumed that a call to `logger.Error` like we have [here](https://github.com/cosmos/ibc-go/blob/28f757a52c1075e78aa16322f1adab35a6e94e7d/modules/apps/27-interchain-accounts/host/ibc_module.go#L129) would execute immediately. I haven't actually checked this yet though.

**Comment by migueldingli1997** [comment]
> Is using the logs for debugging the error a viable alternative for you for the time being?

Yes and no. In a fully local environment we usually have access to the host so in this case the log is accessible, but in an unexpected real-world scenario the host is most likely inaccessible. That being said, thanks for pointing out the logging on the host side; I think I had missed this back then.

**Comment by srdtrk** [comment]
Many users have complained about this. We could add a suffix to errored out events, this way users cannot confuse them with real events but can still debug. This seems to be an ok short term solution until cosmos-sdk introduces a standard to handle this situation. Can we move on to implementation if we have agreement @crodriguezvega @AdityaSripal ?

**Comment by AdityaSripal** [comment]
Hmm seems ok, if we suffix on the key of the event. Definitely a shortgap solution tho

**Comment by srdtrk** [comment]
I've opened [a PR](https://github.com/cosmos/ibc-go/pull/5541) for this using an attribute key prefix after some internal discussion. Do you have any idea which versions we should backport this to @crodriguezvega? I'm guessing v8 and v7

**Comment by crodriguezvega** [comment]
> I've opened [a PR](https://github.com/cosmos/ibc-go/pull/5541) for this using an attribute key prefix after some internal discussion. Do you have any idea which versions we should backport this to @crodriguezvega? I'm guessing v8 and v7

We can do a patch release for this, right? Then yes, backporting to v7 and v8 sounds good.

**Comment by srdtrk** [comment]
Yes, we can do a patch release
