### ISSUE TITLE
Capital Efficient Fee Escrow

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#5509]
We should escrow max(recv+ack, timeout) instead of the full total since that is what will be the max payout.

Discussed as a later improvement at some point but some users have expressed desire for this to exist sooner rather than later. cc: @womensrights

**Comment by crodriguezvega** [comment]
Currently the fee middleware supports assigning [different coins for each of the messages that can be incentivised](https://github.com/cosmos/ibc-go/blob/20312be057ff06c95b11431071a26b8d0c542367/proto/ibc/applications/fee/v1/fee.proto#L14-L35) (and each of the coins can be of a different denomination). We can add the recv and ack fees and use [`sdk.Coins` `Max` function](https://github.com/cosmos/cosmos-sdk/blob/0deaa236c34120ad3865b0fd741202eaad0c3111/types/coin.go#L480) to compare with the timeout fee, but the capital efficiency will be gained if all three fees are of the same denomination; otherwise the `Max` function will return [all three fees if they are different](https://github.com/cosmos/cosmos-sdk/blob/0deaa236c34120ad3865b0fd741202eaad0c3111/types/coin.go#L478).

Does this sound good, @AdityaSripal?

**Comment by srdtrk** [comment]
I was also thinking that maybe we should have `timeout_fee = ack_fee` instead of ``timeout_fee = recv_fee` + ack_fee` since it seems the relayer is doing one half of the work. We can simply refund or **burn** the left over `recv_fee`. (Introduce a burn mechanism to IBC?? O.o)

**Comment by AdityaSripal** [comment]
I would prefer refunding to burning.

I still think my original proposal makes sense

i do think it makes sense to incentivize timeout a bit more because we don't want the packet lifecycle to hang. I don't think there's a danger of relayers just processing timeouts only, since a relayer can always relay before the timeout and take the recv+ack fees for themselves

**Comment by srdtrk** [comment]
How do we want to handle the proto message:
1. Simply ignore `timeout_fee`, mark it deprecated, and use `recv_fee + ack_fee` instead.
2. Use `recv_fee + ack_fee` only if `timeout_fee` is empty. And otherwise, keep our current impl.
3. Remove `timeout_fee` and add a new proto version.

I will go with (1) in the implementation until we make a decision

**Comment by srdtrk** [comment]
How should we handle legacy fees? In my PR, the `timeout_fee` field is depracated and automatically set to zero when writing to storage (we could also enforce it in `ValidateBasic()`). 

However, some legacy fees could be written to the storage with non-zero `timeout_fee` before this upgrade takes place. In these cases, I chose to handle it using the legacy logic. I also think there is a good case to be made for returning the `timeout_fee` to the sender and instead using the new logic to handle fees. What do you think @AdityaSripal ?

**Comment by crodriguezvega** [comment]
@srdtrk Is your idea then that if a timeout happens then the relayer will get `recv_fee + ack_fee`? 

Just for understanding: is the reason to do this that we prevent that the user gets fees refunded after the packet lifecycle completes?

**Comment by srdtrk** [comment]
Yes @crodriguezvega, I see now that I initially misunderstood this issue a bit. But I'd say refunding fees to user is not very capital efficient, I'd rather not have any refunds. But I can easily modify it to the initial design in the issue if we want this.

Also, if we go with the original design, we probably need to do a store migration to differentiate between legacy fees and new fees to handle them separately. With timeout set to zero, we can easily differentiate.

**Comment by srdtrk** [comment]
Since I had an initial misunderstanding of the issue, I will write down what I've implemented and the advantages it has over what was proposed in this issue initially. I can change my implementation to what is proposed in this issue if we still want this.

The current implementation of fee middleware allows `recv_fee, ack_fee, timeout_fee` to all be different and then es-crows `recv_fee + ack_fee + timeout_fee`. The current implementation also refunds either the `timeout_fee` or `recv_fee + ack_fee` depending on whether or not the packet timeouts.

This issue initially proposed that
1. We escrow `max(recv_fee + ack_fee, timeout_fee)` instead of the total.
2. In order to be able to run `Max`, we only allow common denominations between all three fees.
3. We refund the difference `abs(recv_fee + ack_fee - timeout_fee)` depending on whether the packet timeouts.

This runs into the following challenges:
1. This is not fully capital efficient as we still need to process some refunds.
2. Requires store migration. If a chain upgrades from the current version of the fee middleware to the proposed implementation, then there is no way to differentiate between fees that were set in the older version vs the proposed implementation without a store migration.
3. We need to restrict fees to common denominations.

The implementation I made does:
1. Deprecate the `timeout_fee` by setting it to 0.
2. We always escrow `recv_fee + ack_fee`.
3. Timeout relayer is paid `recv_fee + ack_fee` if the packet timeouts instead of `timeout_fee`.

This doesn't run into any of the issues mentioned above since.

**Comment by womensrights** [comment]
Just to clarify, the distinction you are making is that in your implementation you don't specify the timeout fee, instead you only specify recv and ack and then timeout = recv + ack?

Whereas the initial issue suggested you still keep all three fees, a user could specify each of them but then if timeout > recv + ack, you would escrow the timeout amount, then if the packet lifecycle completes successfully you would refund timeout - (recv + ack), if unsuccessful and packet timeouts there would be no refund. Also in this case if recv + ack > timeout the  opposite would be true, on success you would get no refund, on fail you would refund timeout - (recv + ack)? 

I think it is a bit premature to remove the ability for a user to be able to specify each of the three fees granularly before we have actual data on how users end up using the Middleware in practise. I see this issue as just meaning you don't have to escrow more than you will ever spend on the fees rather than changing how you specify them.

**Comment by srdtrk** [comment]
That's right @womensrights. Notice that both suggestions change how fees must be specified. Initial issue requires that they are the same denom (or empty I suppose), whereas this implementation ignores `timeout_fee`.

The initial issue causes more complications when we consider async fees. Suppose a user pays fees in the wrong denom so the packet is stuck. We need to allow the user to submit a different denom using async fees. (I think we can solve this issue, but it is another complication.)

I'm happy to write a second implementation of initial issue, we can use the one we agree on. But I think we should reconsider refunds in that case. I'd be in favour of burning them or even sending them to the community pool like you suggested.

**Comment by womensrights** [comment]
I think this issue can only apply to the case where recv, ack and timeout fees are all in the same denomination and when async fees are also in the same denom - it just matters that within the fee message the demons are the same, between messages it shouldn't matter, you should still be able to improve capital efficiency of escrow for  a given message.

When this isn't the case I don't think we should do anything to increase capital efficiency as it would need an oracle and generally be quite complicated to handle.

**Comment by srdtrk** [comment]
Yeah, I thought about it more and we can probably implement Max in a logical way without requiring denoms to be same. I'll adjust the PR according to the initial issue

**Comment by crodriguezvega** [comment]
As I mentioned in my [comment above](https://github.com/cosmos/ibc-go/issues/5509#issuecomment-1876811795) `sdk.Coins` `Max` function will work even if all three fees have different denoms, it will just simply return all three fees again. It will not allow for the most efficient capital escrowing, but it will work. So for escrowing, I don't think we treat the case of all fees having the same denom as a special case; however, when distributing/refunding fees we will probably need to implement some logic, since the amount to refund the user will be different depending on whether all fees had the same denom or not, I think.

I agree with @womensrights that for now it's better to implement Aditya's proposal and iterate from there.

**Comment by srdtrk** [comment]
Yes, I realized @crodriguezvega. I've already implemented the proposed issue. Will open the PR after I update the e2e tests

**Comment by srdtrk** [comment]
https://github.com/cosmos/ibc-go/pull/5571 r4r 🙂
