### ISSUE TITLE
Remove `Route` method in favour of `Verify(Non)Membership` on client keeper

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6019]
food for thought.. I wonder if we should rather be exposing `VerifyMembership` and `VerifyNonMembership` as client keeper methods now since in other places in 03-connection/04-channel where we did clientState look ups to do things like status, latest height, timestamp at height etc, we're now using client keeper methods which abstract away the router lookups. 

I feel like this might be more in line with 02-client's purpose as a router in general. If dependent modules need to do custom things there is a `GetRouter` method exposed in 02-client 

Interested to hear what others think 🤔

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/6013#discussion_r1528613927_

**Comment by crodriguezvega** [comment]
I believe this is what needs to be done, please correct me if I am wrong:

- [ ] Remove [`Route` function from `ClientKeeper` interface](https://github.com/cosmos/ibc-go/blob/35181d87c6aabd10a89346586b9f67cee21acd69/modules/core/03-connection/types/expected_keepers.go#L21).
- [ ] Add functions to `ClientKeeper` interface:

```golang
VerifyMembership(
  ctx sdk.Context,
  clientID string,
  height Height,
  delayTimePeriod uint64,
  delayBlockPeriod uint64,
  proof []byte,
  path Path,
  value []byte,
) error
VerifyNonMembership(
  ctx sdk.Context,
  clientID string,
  height Height,
  delayTimePeriod uint64,
  delayBlockPeriod uint64,
  proof []byte,
  path Path,
) error
```

- [ ] Implement the above functions. Get the client module like [this](https://github.com/cosmos/ibc-go/blob/35181d87c6aabd10a89346586b9f67cee21acd69/modules/core/02-client/keeper/keeper.go#L396-L408) (this could be extracted to a helper unexported function, since it will be repeated in a few places), and then call the corresponding function.
- [ ] Use the functions implemented above in the `Verify...` functions of 03-connection.
