### ISSUE TITLE
ICA host enabled in genesis as default 

### ISSUE THREAD

**Issue by seantking** [cosmos/ibc-go#6324]
## Summary of Bug

Yo. I'm not sure if it's intentional or not but even without wiring up the host module for ICA in app.go the genesis will always be pre-filled with:

```
"host_genesis_state": {
     "active_channels": [],
     "interchain_accounts": [],
     "port": "icahost",
      "params": {
       "host_enabled": true,
        "allow_messages": [
          "*"
        ]
  }
```

I'm guessing this effects nothing as there is no host module wired up but I found it confusing. Any reason for this or is it just a side effect? 

## Version

latest

## Steps to Reproduce

Remove host module wiring and init a new genesis. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
Yeah, this is side effect of having both controller and host genesis under the same sdk module. I'm assuming you're using icacontroller only, but seeing this in genesis.json without wiring up the host keeper etc? 

Chains can just switch this to false, but there won't be any other unintended side effects. Unfortunately you can't really programatically switch the param to false - since the [genesis is never actually initialised](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/module.go#L162-L164) this object exists only the genesis.json is never actually set in the db. You should be able to verify that with: `$binary q interchain-accounts host params`

**Comment by seantking** [comment]
Got it thanks.

**Comment by damiannolan** [comment]
Sometime in the future there may be small chance we have to split host/controller into separate sdk modules as depinject doesn't support multiple kvstore keys, and then this would no longer be showing up in the json file. Unsure if that will happen or not, there's a potential workaround/hack also suggested for that problem but its outside the scope of this issue.

Since there's no actionable items I'll close this.
