### ISSUE TITLE
Move decision on async handling to ibc module's `OnRecv` callback.

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6556]
Instead of returning boolean from Keeper OnRecvPacket to signal async ack, check if packet data in IBC module OnRecvPacket has a forwarding path.

Surfaced during internal walkthrough of ics20 v2 forwarding (commit [efcfa5d](https://github.com/cosmos/ibc-go/tree/efcfa5d877567731f6b4ff8dbd063a34ede5de00))

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by damiannolan** [comment]
It could be nice or worth looking into to structure things within ibc_module.go something like:

```
// decode packet data

// keeper.OnRecvPacket()

// if data.ForwardingPath != nil { keeper.ForwardPacket() } 
```

But I think there's some stuff done to work `coins` whether they are recver source or not before forwarding, so that logic would either need to be duplicated or returned. 

Otherwise, we could still sweep the forwarding logic into a priv func within keeper.
