### ISSUE TITLE
Use a transfer module account as an intermediary address for forwards

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#6561]
Reference code:

https://github.com/cosmos/ibc-go/blob/efcfa5d877567731f6b4ff8dbd063a34ede5de00/modules/apps/transfer/types/keys.go#L86-L97

Surfaced during internal walkthrough of ics20 v2 forwarding (commit [efcfa5d](https://github.com/cosmos/ibc-go/tree/efcfa5d877567731f6b4ff8dbd063a34ede5de00))

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by srdtrk** [comment]
I recommend we switch to a module account. In SDK v0.50, bank keeper's [`BurnCoins`](https://github.com/cosmos/cosmos-sdk/blob/v0.50.7/x/bank/keeper/keeper.go#L47) method only works on module accounts. This is [extended to any account](https://github.com/cosmos/cosmos-sdk/blob/78327f40c5ad6e31a056c662e2046cbf1b6ed691/x/bank/keeper/keeper.go#L48) in the next version of the SDK.

The simplifications I'm doing in https://github.com/cosmos/ibc-go/issues/6558 would benefit from the ability to use `BurnCoins` directly

**Comment by colin-axner** [comment]
Yes we should use SDK module accounts (for forwarding escrow) :+1: 

Context on why transfer doesn't use module accounts already is that transfer was developed before module accounts was a feature. Migrating all escrow addresses is quite sensitive (and not necessarily beneficial given that the current construction is safe). But this historical baggage should not inform our current decisions when possible. We also use module accounts in [ics29](https://github.com/cosmos/ibc-go/blob/9a34c317cf31130c3b2cb2dfe069b4f600f49088/modules/apps/29-fee/keeper/escrow.go#L29)

**Comment by colin-axner** [comment]
Did some extra thinking about needing to create isolated buckets based on the hop port/channel, but it doesn't seem to provide any security benefits. Transfer escrow addresses being indexed by destination port/channel is useful since it creates fault tolerance. If connection to chainB goes malicious, chainB cannot steal funds in escrow for chainC

Given that the only funds moving through the forward address go through the normal transfer logic, I don't see how a malicious chain could generate some sequence of steps to steal from funds deposited through the forward address. In addition, funds should never be stored in the forward address after the transfer message completes execution. 

When receiving a packet, tokens are either unescrowed or minted to the forwarding address which will then either escrow or burn. Upon refunds, tokens are either unescrowed or minted to the forwarding address, which will then either be escrow or burned when reversing to the original sender.

**Comment by crodriguezvega** [comment]
Closed by #6688
