### ISSUE TITLE
ibc-go v.7.5.0 (and v7.6.0) breaks ICS27 backwards compatibility by default

### ISSUE THREAD

**Issue by AmitPr** [cosmos/ibc-go#6714]
# Summary of Bug
`7.5.0` introduces channel ordering options in the interchain accounts controller module. Older versions of ibc-go will fail to create the ICA channel if the ordering is not `ORDER_ORDERED`. However, the default ordering in `NewMsgRegisterInterchainAccount` is `ORDER_UNORDERED`, meaning that existing code that has been upgraded to ibc-go `>=7.5.0` will no longer be compatible with older chains.

Relevant code:
https://github.com/cosmos/ibc-go/blob/b605529d6ccd1170e3d4bdec9fb9b79fd22a2141/modules/apps/27-interchain-accounts/controller/types/msgs.go#L34-L41

## Expected Behaviour
Channels are `ORDER_ORDERED` by default, to preserve compatibility with older ibc-go versions

## Version
Observed on ibc-go `7.6.0` (Kujira)

## Steps to Reproduce
N/A

**Comment by AmitPr** [comment]
Note: I haven't taken a look at ibc-go v8 and beyond, as we are not yet using it on Kujira.

**Comment by crodriguezvega** [comment]
Hi @AmitPr. This change was documented in the release notes of [v7.5.0](https://github.com/cosmos/ibc-go/releases/tag/v7.5.0) and in the [documentation](https://github.com/cosmos/ibc-go/blob/main/docs/versioned_docs/version-v7.6.x/02-apps/02-interchain-accounts/10-legacy/03-keeper-api.md#registerinterchainaccount). You can keep the previous behaviour by setting the ordering to `UNORDERED` in the `MsgRegisterInterchainAccount`, or if you are using the legacy API, you can also use the `RegisterInterchainAccountWithOrdering` function to explicitly set the ordering to `UNORDERED`. Does this help?

**Comment by AmitPr** [comment]
@crodriguezvega the issue is that the default method for creating `MsgRegisterInterchainAccount` creates an `UNORDERED` channel, which is **not backwards compatible**, since previous versions of ibc-go default to `ORDERED`.

A module we have creates ICAs, and this default behavior **silently** broke the functionality and backwards compatibility of this module because of the change in default behavior. I will also note that this breakage was implemented in a minor semver upgrade.

**Comment by crodriguezvega** [comment]
Hi @AmitPr. Sorry for the late reply. We discussed this internally and we agree that we should probably not have introduced this change in a minor release, but the reason why we did it is because reopening ordered channels that close due to timeouts was one of the biggest complaints about ICA, so we decided to address it as soon as possible. We realise that this change in the default behaviour might be a bit surprising for existing users of ICA, but using unordered channels as the default for new ICA channels provides a better experience. We take for the future the learning point that we shouldn't make behavioural changes in minor releases, but we will not make a new minor release now to change back the ordering, since it would potentially make things even more confusing for our users.

I will close the issue now, but thanks for raising this problem. Feel free still to leave a comment if you have any more thoughts.
