### ISSUE TITLE
Retrieving data using REST API - how to determine time before IBC client expires?

### ISSUE THREAD

**Issue by napelvs** [cosmos/ibc-go#6893]
Hey everyone.

I'm developing an app where I need to know the time left for an IBC client to expire. Given my research, I've found the only possible way to get this piece of information is to retrieve:

1. Trusting Period of the client
2. Last TX that updated the IBC client

The first is easily accessible, but I'm having issues retrieving the second one.

This is what I have right now:

```[osmosis_rest_api_url]/cosmos/tx/v1beta1/txs?order_by=2&events=send_packet.packet_src_channel='channel-0'&events=send_packet.packet_src_port='transfer'&events=send_packet.packet_dst_channel='channel-141'&message.action='/ibc.core.client.v1.MsgUpdateClient'&limit=1```

The issue I run into is that the `message.action='/ibc.core.client.v1.MsgUpdateClient'` parameter in the query doesn't work. Also, I see that the `chain_id` value in the json response doesn't align with the channels mentioned in the query. It should be either Osmosis or Cosmos, but I get random chains I'm not interested in.

While help in achieving this query to respond the way I expect is greatly appreciated, further information into how to filter information would be paramount in making sure I don't need to ask around every time. I want to be as self-sufficient as possible. Send in any helpful documentation and tips on anything related to REST API calls and filtering the JSON responses.

Thank you for reading.

**Comment by crodriguezvega** [comment]
Hi @napelvs. I think there are a couple of tweaks that you need on your query to make it work:

1. The message `MsgUpdateClient` is usually bundled with `MsgRecvPacket`, so the event that you will see is for receive packet, not send packet; therefore you need to change the event search from `send_packet` to `recv_packet`.
2. When the light client for the Cosmos Hub on Osmosis is updated upon a packet receive the source channel is the channel end on Cosmos Hub (`channel-141`) and the destination channel is the channel end on Osmosis (`channel-0`).

So with these two modifications then the query would look like this:

`https://rest.cosmos.directory/osmosis/cosmos/tx/v1beta1/txs?order_by=2&events=recv_packet.packet_src_channel='channel-141'&events=recv_packet.packet_src_port='transfer'&events=recv_packet.packet_dst_channel='channel-0'&message.action='/ibc.core.client.v1.MsgUpdateClient'&limit=1`

Please give it a try, because I think this returns the information you're after. Let me know if it works for you and then I will close the issue. Thanks!

**Comment by napelvs** [comment]
Hi @crodriguezvega. Thank you for your answer!

I've looked into the query provided by you, and it retrieves the data I need.

From my understanding, this query should always respond with the latest `MsgUpdateClient` TX that occurred on this specific combination of src/dst channels. Is that right?

My intent is to base the time to expiration of a client on this query - specifically the time of the latest `MsgUpdateClient` (which I hope this query correctly retrieves).

**Comment by crodriguezvega** [comment]
> From my understanding, this query should always respond with the latest MsgUpdateClient TX that occurred on this specific combination of src/dst channels. Is that right?

Yes, I think that's correct!

> My intent is to base the time to expiration of a client on this query - specifically the time of the latest MsgUpdateClient (which I hope this query correctly retrieves).

You should based it on time in the header included in `MsgUpdateClient`, right?

**Comment by napelvs** [comment]
> You should based it on time in the header included in MsgUpdateClient, right?

Yes, that's my plan. Ok, that answer my query. I will now go ahead and close this discussion!

Thank you for the assistance!
