### ISSUE TITLE
Disallow unknown fields in 29-fee ack

### ISSUE THREAD

**Issue by bznein** [cosmos/ibc-go#6921]

**Comment by damiannolan** [comment]
@colin-axner was the concern here that some counterparty to populate additional fields into the acknowledgement and have that emitted from ibc core in events? https://github.com/cosmos/ibc-go/blob/main/modules/core/04-channel/types/acknowledgement.go#L88-L92

The request would be to implement a custom unmarshalJSON function with a new `jsonpb.Unmarshaller` https://pkg.go.dev/github.com/golang/protobuf/jsonpb#Unmarshaler with `AllowUnknownFields` as false, correct?

I think this is already the case with the proto codec in cosmos-sdk here: https://github.com/cosmos/cosmos-sdk/blob/main/codec/proto_codec.go#L204 

The field is not filled in so should be default to false

**Comment by damiannolan** [comment]
Aha, thanks @DimitrisJim. So as is stands we're json marshaling the ack and proto3 json unmarshaling. I'd still be curious to see how this performs since the proto3 json unmarshaler should disallow unknown fields too.

But the general ask for this issue is adding:

```golang
func (ack IncentivizedAcknowledgement) UnmarshalJSON(bz []byte) error {
   // same impl as FungibleTokenPacketData
}
```
ref: https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/encoding.go#L9
