### ISSUE TITLE
Add version wrap/unwrap interfaces to handle backwards compatibility 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#6954]
## Summary

initial [investigation](https://github.com/cosmos/ibc-go/tree/colin/port-router-version-investigation). Should be swept into a classic.BackwardsCompatibleModule interface

Must handle:
- unwrapping channel version given an ordered list of callbacks
- wrapping channel version given an ordered list of callbacks
- supplying the correct application version in channel handshakes and packet processing steps

Note: needs access to ctx, portID, channelID

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
I think I really like the idea of the relayers providing an additional mapping, I think it makes a lot of less and would lower the overall complexity.

I've never been a fan of the wrapped channel version, since it's quite error prone. A simple `map[string]string` should do the trick, be simple to implement and not add greatly reduce the complexity compared to the current implementation.

I think it will be required to store these unwrapped versions in state for situations such as determining if a v1 transfer channel (on an ibc-go version that supports v2) can process a v2 packet.
