### ISSUE TITLE
Replace github.com/pkg/errors with stdlib errors

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#709]
## Summary

The package `github.com/pkg/errors` is hosted in an unmaintained and archived repository.
This package has been taken over and included within the Go standard library.

## Proposal

Usage of `github.com/pkg/errors` should be replaced by the Go standard library package: `errors`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by dkmccandless** [comment]
I'm interested in opening a PR (my first) to fix this issue, but I have been unable to push my branch to the repo. I'm guessing it's a question of access rights, which I'm not familiar with. If it wouldn't be out of place, please advise what I can do to contribute.

**Comment by crodriguezvega** [comment]
> I'm interested in opening a PR (my first) to fix this issue, but I have been unable to push my branch to the repo. I'm guessing it's a question of access rights, which I'm not familiar with. If it wouldn't be out of place, please advise what I can do to contribute.

Thank you for your interest in contributing! The easiest for you would to fork the repository and do the changes in a branch there. Once you're done you can open a PR to the main branch of this repository. If you are not familiar with this process, please check out [GitHub's documentation on creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by dkmccandless** [comment]
Calls to `github.com/pkg/errors` are being made in two files, [modules/core/02-client/client/cli/tx.go](https://github.com/cosmos/ibc-go/blob/main/modules/core/02-client/client/cli/tx.go) and [modules/core/03-connection/client/utils/utils.go](https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/client/utils/utils.go). The calls in these files are to two functions: 
- `errors.New`: This is identical to the corresponding function in the standard library's `errors` package; the fix is trivial.
- `errors.Wrap`: This functionality is subsumed in the standard library by `fmt.Errorf`'s `%w` verb. `fmt.Errorf("error message: %w", err)` is equivalent to the old `errors.Wrap(err, "error message")`.

`github.com/pkg/errors` remains as an indirect dependency in `go.mod` because it is used by `cosmos-sdk`.

**Comment by crodriguezvega** [comment]
Thanks for the analysis! I think it should be fine to replace `errors.Wrap` with `fmt.Errorf`. What do you think, @colin-axner?

And if the Cosmos SDK uses `github.com/pkg/errors` then we will have to live with the transient dependency... But we can also open an issue in the SDK repository and ask to deprecate the usage of `github.com/pkg/errors`.

**Comment by colin-axner** [comment]
All sounds good to me!
