### ISSUE TITLE
Question on ica module

### ISSUE THREAD

**Issue by romelukaku** [cosmos/ibc-go#712]
## Summary
This is more of a question than a proposal 

ICA module create an ibc channel for each interchain accounts
Can we make it so that this ICA module only use one channel like the transfer module, one channel for all interchain accounts

## Problem Definition

- The process of creating an ibc channel is time and resource consuming as we all know. Right now ica module require us to create an ibc channel for each interchain account so 1000 accounts means 1000 channels.

- User who want to use ica will have to wait for their ica channel to be created by a relayer

- Relayer will have a hard time handling a bunch of channels at once

## Proposal

We change the logic of this module so that it only use one channel for all accounts. I think we can still remain the same level of security while avoid a lot of complication as mentioned above 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Hi! Good question!

Each interchain account must have its associated packets sent/received in order. That is, if I own interchain account X, each packet which executes transactions on behalf of that account must have ordering (just like any account). 

Core IBC currently only supports UNORDERED and ORDERED channels. Since we need ordering, UNORDERED channels are out the question. Since we are using ORDERED channels, if we had a single ordered channel for all interchain accounts created, then all packets before my packet is sent need to be relayed before mine can be received. This means I might be forced to pay for the relaying of packets being used as a DoS attack in order to have mine received. For this reason we have a single interchain account per channel

In the ideal world we would have a partially ordered channel which is like an ordered channel which can support many accounts and only enforce ordering for each account rather than for all packets on the channel (thus removing the DoS vector). Due to time and resource constraints, we felt it was better to ship interchain accounts with the current mechanism of one channel per account than to delay by adding a new channel type to core IBC

I'm going to close this issue since there are no action items

**Comment by romelukaku** [comment]
that makes sense now, thank you
